<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <Import Project="..\..\CSharpEssentials.Endpoints\build\CSharpEssentials.Endpoints.props" />

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CSharpEssentials.Endpoints\CSharpEssentials.Endpoints.csproj" />
    <ProjectReference Include="..\CSharpEssentials.Tests.Fixtures.EndpointsA\CSharpEssentials.Tests.Fixtures.EndpointsA.csproj" />
    <ProjectReference Include="..\..\CSharpEssentials.Endpoints.Generators\CSharpEssentials.Endpoints.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
