using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace CSharpEssentials.Enums.Generators;

/// <summary>
/// Writes the generated extension class, the per-assembly registry and the <c>ModuleInitializerAttribute</c> polyfill.
/// </summary>
internal static class StringEnumSourceWriter
{
    public const string RegistryClassName = "__CSharpEssentialsEnumRegistry";

    private const string Enums = "global::CSharpEssentials.Enums";

    private static readonly string GeneratedCode =
        $"[global::System.CodeDom.Compiler.GeneratedCode(\"CSharpEssentials.Enums.Generators\", \"{typeof(StringEnumSourceWriter).Assembly.GetName().Version}\")]";

    public static string WriteExtensions(EnumModel model, GeneratorSettings settings)
    {
        EnumMemberModel[] members = [.. model.Members];
        EnumMemberModel[] distinct = Distinct(members);
        string type = model.FullyQualifiedName;
        bool modern = settings.SupportsRegistration;
        string nullableString = settings.SupportsNullable ? "string?" : "string";
        string[] wireNames = modern ? WireNames(model, settings) : [];

        Writer w = new();
        w.Line("// <auto-generated/>");
        if (settings.SupportsNullable)
            w.Line("#nullable enable");
        w.Line();
        bool hasNamespace = model.Namespace.Length > 0;
        if (hasNamespace)
        {
            w.Line("namespace " + model.Namespace);
            w.Open();
        }

        if (modern)
        {
            w.Line("/// <summary>Generated helpers for <see cref=\"" + type + "\"/>.</summary>");
            w.Line(GeneratedCode);
        }

        w.Line((model.IsPublic ? "public" : "internal") + " static class " + model.ExtensionsClassName);
        w.Open();

        for (int i = 0; i < members.Length; i++)
        {
            EnumMemberModel member = members[i];
            w.Line("public const string " + member.Name + "SnakeCase = " + Literal(EnumWireNaming.ToLegacySnakeCase(member.Name)) + ";");
            w.Line("public const string " + member.Name + "KebabCase = " + Literal(EnumWireNaming.ToLegacyKebabCase(member.Name)) + ";");
            if (modern)
                w.Line("public const string " + member.Name + "WireName = " + Literal(wireNames[i]) + ";");
        }

        if (members.Length > 0)
            w.Line();

        if (modern)
            WriteWireHelpers(w, model, distinct, members, wireNames);

        WriteSwitch(w, model, distinct, "ToOptimizedString", null, static m => Literal(m.Name), "value.ToString()");
        WriteSwitch(w, model, distinct, "ToSnakeCase", modern ? "Use ToWireName()" : null, static m => Literal(EnumWireNaming.ToLegacySnakeCase(m.Name)), "ToSnakeCaseFallback(value.ToOptimizedString())");
        WriteSwitch(w, model, distinct, "ToKebabCase", null, static m => Literal(EnumWireNaming.ToLegacyKebabCase(m.Name)), "ToKebabCaseFallback(value.ToOptimizedString())");
        WriteSwitch(w, model, distinct, "ToLowerCase", null, static m => Literal(m.Name) + ".ToLowerInvariant()", "value.ToString().ToLowerInvariant()");
        WriteSwitch(w, model, distinct, "ToUpperCase", null, static m => Literal(m.Name) + ".ToUpperInvariant()", "value.ToString().ToUpperInvariant()");
        WriteLegacyLookups(w, model, members, nullableString, modern);
        WriteFallbackHelpers(w);

        w.Close();
        if (hasNamespace)
            w.Close();

        return w.ToString();
    }

    /// <summary>One element of the generated <c>RegisterRange</c> array.</summary>
    public static string RegistryEntry(string enumType, string extensionClass) =>
        "new(typeof(" + enumType + "), " + extensionClass + ".__CreateEnumInfo),";

    public static string WriteRegistry(EquatableArray<string> entries)
    {
        Writer w = new();
        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line();
        w.Line("/// <summary>Registers the generated enum metadata of this assembly.</summary>");
        w.Line(GeneratedCode);
        w.Line("internal static class " + RegistryClassName);
        w.Open();
        w.Line("/// <summary>Registers every <c>[StringEnum]</c> enum of this assembly in <see cref=\"" + Enums + ".EnumMetadata\"/>.</summary>");
        w.Line("[global::System.Runtime.CompilerServices.ModuleInitializer]");
        w.Line("internal static void Register()");
        w.Open();
        w.Line(Enums + ".EnumMetadata.RegisterRange(new global::System.Collections.Generic.KeyValuePair<global::System.Type, global::System.Func<" + Enums + ".IEnumInfo>>[]");
        w.Open();
        foreach (string entry in entries)
        {
            w.Line(entry);
        }

        w.Close(");");
        w.Close();
        w.Close();
        return w.ToString();
    }

    public static string WriteModuleInitializerPolyfill()
    {
        Writer w = new();
        w.Line("// <auto-generated/>");
        w.Line();
        w.Line("namespace System.Runtime.CompilerServices");
        w.Open();
        w.Line(GeneratedCode);
        w.Line("[global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]");
        w.Line("internal sealed class ModuleInitializerAttribute : global::System.Attribute");
        w.Open();
        w.Close();
        w.Close();
        return w.ToString();
    }

    public static string[] WireNames(EnumModel model, GeneratorSettings settings) =>
        WireNames(model.Members, model.Naming, settings.ProjectNaming);

    public static string[] WireNames(IReadOnlyList<EnumMemberModel> members, int enumNaming, int projectNaming)
    {
        int naming = EnumWireNaming.Resolve(enumNaming, projectNaming);
        string[] names = new string[members.Count];
        for (int i = 0; i < names.Length; i++)
        {
            EnumMemberModel member = members[i];
            names[i] = member.DeclaredWireName ?? EnumWireNaming.Convert(member.Name, naming);
        }

        return names;
    }

    private static void WriteWireHelpers(Writer w, EnumModel model, EnumMemberModel[] distinct, EnumMemberModel[] members, string[] wireNames)
    {
        string type = model.FullyQualifiedName;
        string info = Enums + ".EnumInfo<" + type + ">";
        string metadata = Enums + ".EnumMetadata.Get<" + type + ">()";

        w.Line("private static readonly " + Enums + ".EnumConventions __WireReadConventions = " + Enums
            + ".EnumConventions.Default with { UnknownValue = " + Enums + ".UnknownEnumValueHandling.Reject };");
        w.Line();

        w.Line("/// <summary>The canonical wire name. Throws <see cref=\"" + Enums + ".EnumValueException\"/> for undefined values.</summary>");
        w.Line("public static string ToWireName(this " + type + " value)");
        w.Open();
        if (model.IsFlags)
        {
            // Flags output never uses composite members (design section 5.1), so the formatter decomposes every value.
            w.Line("return " + metadata + ".Format(value, " + Enums + ".EnumWireFormat.String);");
        }
        else
        {
            w.Line("switch (value)");
            w.Open();
            foreach (EnumMemberModel member in distinct)
            {
                w.Line("case " + ValueExpression(model, member) + ":");
                w.Line("    return " + member.Name + "WireName;");
            }

            w.Line("default:");
            w.Line("    return " + metadata + ".Format(value, " + Enums + ".EnumWireFormat.String);");
            w.Close();
        }

        w.Close();
        w.Line();

        w.Line("/// <summary>Parses with the data read rules (every known spelling, defined numbers), without the fallback member.</summary>");
        w.Line("public static bool TryParseWire(string? text, out " + type + " value)");
        w.Open();
        w.Line("if (text is null)");
        w.Open();
        w.Line("value = default;");
        w.Line("return false;");
        w.Close();
        w.Line();
        w.Line("return " + metadata + ".TryParse(text, " + Enums + ".EnumReadMode.Data, __WireReadConventions, out value, out _);");
        w.Close();
        w.Line();

        w.Line("/// <summary>Parses like <see cref=\"TryParseWire\"/> and throws <see cref=\"" + Enums + ".EnumValueException\"/> on failure.</summary>");
        w.Line("public static " + type + " ParseWire(string? text)");
        w.Open();
        w.Line(info + " info = " + metadata + ";");
        w.Line("if (text is null)");
        w.Line("    throw new " + Enums + ".EnumValueException(info.CreateError(null, " + Enums + ".EnumReadMode.Data));");
        w.Line("if (info.TryParse(text, " + Enums + ".EnumReadMode.Data, __WireReadConventions, out " + type + " value, out " + Enums + ".EnumValueError? error))");
        w.Line("    return value;");
        w.Line("throw new " + Enums + ".EnumValueException(error);");
        w.Close();
        w.Line();

        w.Line("/// <summary>Whether <paramref name=\"value\"/> is a defined member" + (model.IsFlags ? " or a combination of defined flags" : string.Empty) + ".</summary>");
        w.Line("public static bool IsDefined(this " + type + " value) => " + metadata + ".IsDefined(value);");
        w.Line();

        w.Line("internal static " + info + " __CreateEnumInfo()");
        w.Open();
        w.Line("return new " + info + "(");
        w.Line("    new " + Enums + ".EnumMemberInfo<" + type + ">[]");
        w.Line("    {");
        for (int i = 0; i < members.Length; i++)
        {
            EnumMemberModel member = members[i];
            StringBuilder line = new();
            line.Append("        new ").Append(Enums).Append(".EnumMemberInfo<").Append(type).Append(">(")
                .Append(ValueExpression(model, member)).Append(", ")
                .Append(member.RawValue.ToString(CultureInfo.InvariantCulture)).Append("UL, ")
                .Append(Literal(member.Name)).Append(", ")
                .Append(member.Name).Append("WireName)");
            AppendInitializer(line, member, Aliases(member, wireNames[i]));
            w.Line(line.Append(',').ToString());
        }

        w.Line("    },");
        w.Line("    static v => unchecked((ulong)(long)v),");
        w.Line("    static r => unchecked((" + type + ")(long)r),");
        w.Line("    " + (model.IsFlags ? "true" : "false") + ",");
        w.Line("    (" + Enums + ".EnumStorage)" + model.Storage.ToString(CultureInfo.InvariantCulture) + ");");
        w.Close();
        w.Line();
    }

    private static void AppendInitializer(StringBuilder line, EnumMemberModel member, List<string> aliases)
    {
        List<string> parts = [];
        if (aliases.Count > 0)
            parts.Add("Aliases = new string[] { " + string.Join(", ", aliases.Select(Literal)) + " }");
        if (member.Description is not null)
            parts.Add("Description = " + Literal(member.Description));
        if (member.IsObsolete)
            parts.Add("IsObsolete = true");
        if (member.IsFallback)
            parts.Add("IsFallback = true");
        if (parts.Count > 0)
            line.Append(" { ").Append(string.Join(", ", parts)).Append(" }");
    }

    private static List<string> Aliases(EnumMemberModel member, string wireName)
    {
        List<string> aliases = [.. member.Aliases];
        string legacy = EnumWireNaming.ToLegacySnakeCase(member.Name);
        if (!string.Equals(legacy, wireName, StringComparison.Ordinal) && !aliases.Contains(legacy, StringComparer.Ordinal))
            aliases.Add(legacy);
        return aliases;
    }

    private static void WriteSwitch(Writer w, EnumModel model, EnumMemberModel[] distinct, string methodName, string? obsolete,
        Func<EnumMemberModel, string> result, string fallback)
    {
        if (obsolete is not null)
            w.Line("[global::System.Obsolete(" + Literal(obsolete) + ")]");
        w.Line("public static string " + methodName + "(this " + model.FullyQualifiedName + " value)");
        w.Open();
        w.Line("switch (value)");
        w.Open();
        foreach (EnumMemberModel member in distinct)
        {
            w.Line("case " + ValueExpression(model, member) + ":");
            w.Line("    return " + result(member) + ";");
        }

        w.Line("default:");
        w.Line("    return " + fallback + ";");
        w.Close();
        w.Close();
        w.Line();
    }

    private static void WriteLegacyLookups(Writer w, EnumModel model, EnumMemberModel[] members, string nullableString, bool modern)
    {
        string type = model.FullyQualifiedName;

        w.Line("public static bool IsDefined(string name)");
        w.Open();
        w.Line("switch (name)");
        w.Open();
        foreach (EnumMemberModel member in members)
        {
            w.Line("case " + Literal(member.Name) + ":");
        }

        if (members.Length > 0)
            w.Line("    return true;");
        w.Line("default:");
        w.Line("    return false;");
        w.Close();
        w.Close();
        w.Line();

        if (modern)
            w.Line("[global::System.Obsolete(\"Use TryParseWire/ParseWire\")]");
        w.Line("public static bool TryParse(" + nullableString + " name, out " + type + " value)");
        w.Open();
        if (members.Length > 0)
        {
            w.Line("switch (name)");
            w.Open();
            foreach (EnumMemberModel member in members)
            {
                w.Line("case " + Literal(member.Name) + ":");
                w.Line("    value = " + ValueExpression(model, member) + ";");
                w.Line("    return true;");
            }

            w.Close();
            w.Line();
        }

        w.Line(model.UnderlyingType + " numericValue;");
        w.Line("if (name != null && " + model.UnderlyingType + ".TryParse(name, out numericValue))");
        w.Open();
        w.Line("value = (" + type + ")numericValue;");
        w.Line("return true;");
        w.Close();
        w.Line();
        w.Line("value = (" + type + ")0;");
        w.Line("return false;");
        w.Close();
        w.Line();

        if (modern)
            w.Line("[global::System.Obsolete(\"Use TryParseWire/ParseWire\")]");
        w.Line("public static " + type + " Parse(" + nullableString + " name)");
        w.Open();
        w.Line(type + " value;");
        w.Line("if (TryParse(name, out value))");
        w.Open();
        w.Line("return value;");
        w.Close();
        w.Line();
        w.Line("throw new global::System.ArgumentException(\"Requested value '\" + name + \"' was not found.\");");
        w.Close();
        w.Line();

        w.Line("public static string[] GetNames()");
        w.Open();
        w.Line("return new string[] { " + string.Join(", ", members.Select(static m => Literal(m.Name))) + " };");
        w.Close();
        w.Line();

        w.Line("public static " + type + "[] GetValues()");
        w.Open();
        w.Line("return new " + type + "[] { " + string.Join(", ", members.Select(m => ValueExpression(model, m))) + " };");
        w.Close();
        w.Line();

        w.Line("public static " + model.UnderlyingType + " AsUnderlyingType(this " + type + " value)");
        w.Open();
        w.Line("return (" + model.UnderlyingType + ")value;");
        w.Close();
        w.Line();
    }

    private static void WriteFallbackHelpers(Writer w)
    {
        WriteFallbackHelper(w, "ToSnakeCaseFallback", '_');
        w.Line();
        WriteFallbackHelper(w, "ToKebabCaseFallback", '-');
        w.Line();
        w.Line("private static bool CheckCategory(global::System.Globalization.UnicodeCategory previous, global::System.Globalization.UnicodeCategory current)");
        w.Open();
        w.Line("return previous != current && (current == global::System.Globalization.UnicodeCategory.UppercaseLetter || current == global::System.Globalization.UnicodeCategory.DecimalDigitNumber || IsSpecialCharacter(previous) && !IsSpecialCharacter(current));");
        w.Close();
        w.Line();
        w.Line("private static bool IsSpecialCharacter(global::System.Globalization.UnicodeCategory category)");
        w.Open();
        w.Line("return category != global::System.Globalization.UnicodeCategory.UppercaseLetter");
        w.Line("    && category != global::System.Globalization.UnicodeCategory.LowercaseLetter");
        w.Line("    && category != global::System.Globalization.UnicodeCategory.DecimalDigitNumber;");
        w.Close();
    }

    private static void WriteFallbackHelper(Writer w, string methodName, char separator)
    {
        w.Line("private static string " + methodName + "(string input)");
        w.Open();
        w.Line("if (string.IsNullOrEmpty(input)) return input;");
        w.Line("global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length + 4);");
        w.Line("global::System.Globalization.UnicodeCategory previous = global::System.Globalization.UnicodeCategory.OtherSymbol;");
        w.Line("bool isFirst = true;");
        w.Line("for (int i = 0; i < input.Length; i++)");
        w.Open();
        w.Line("char c = input[i];");
        w.Line("global::System.Globalization.UnicodeCategory current = char.GetUnicodeCategory(c);");
        w.Line("bool insertSeparator = CheckCategory(previous, current);");
        w.Line("bool isSpecial = IsSpecialCharacter(current);");
        w.Line("if (!isSpecial)");
        w.Open();
        w.Line("if (insertSeparator && !isFirst) sb.Append('" + separator + "');");
        w.Line("sb.Append(char.ToLowerInvariant(c));");
        w.Line("isFirst = false;");
        w.Close();
        w.Line("previous = current;");
        w.Close();
        w.Line("return sb.ToString();");
        w.Close();
    }

    /// <summary>The first member of every value, so switch statements have no duplicate case labels.</summary>
    private static EnumMemberModel[] Distinct(EnumMemberModel[] members)
    {
        HashSet<ulong> seen = [];
        return [.. members.Where(member => seen.Add(member.RawValue))];
    }

    // A member declared as @class has the name "class"; member access needs the escape again.
    private static string Identifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None ? name : "@" + name;

    /// <summary>
    /// The member access, or a cast of the number for <c>[Obsolete]</c> members so generated code does not raise CS0618.
    /// </summary>
    private static string ValueExpression(EnumModel model, EnumMemberModel member)
    {
        if (!member.IsObsolete)
            return model.FullyQualifiedName + "." + Identifier(member.Name);

        string number;
        if (model.IsSigned)
        {
            long value = unchecked((long)member.RawValue);
            string suffix = model.UnderlyingType == "long" ? "L" : string.Empty;
            string digits = value == long.MinValue ? "-9223372036854775807L - 1L" : value.ToString(CultureInfo.InvariantCulture) + suffix;
            number = value < 0 ? "(" + digits + ")" : digits;
        }
        else
        {
            number = member.RawValue.ToString(CultureInfo.InvariantCulture) + (model.UnderlyingType == "ulong" ? "UL" : string.Empty);
        }

        return "(" + model.FullyQualifiedName + ")" + number;
    }

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private sealed class Writer
    {
        private readonly StringBuilder _sb = new();
        private int _indent;

        public void Line(string text = "")
        {
            if (text.Length > 0)
                _sb.Append(' ', _indent * 4).Append(text);
            _sb.Append('\n');
        }

        public void Open()
        {
            Line("{");
            _indent++;
        }

        public void Close(string suffix = "")
        {
            _indent--;
            Line("}" + suffix);
        }

        public override string ToString() => _sb.ToString();
    }
}
