using System.Text.Json.Nodes;
using CSharpEssentials.AspNetCore;
using CSharpEssentials.Enums;
using FluentAssertions;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.OpenApi;
using Swashbuckle.AspNetCore.Swagger;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace CSharpEssentials.Tests.AspNetCore;

/// <summary>The state of a review item.</summary>
[StringEnum]
internal enum SwReviewState
{
    Open,
    Closed
}

internal sealed class SwReviewItem
{
    /// <summary>The current state.</summary>
    public SwReviewState State { get; set; }

    public SwReviewState Previous { get; set; }

    public SwReviewState? Next { get; set; }
}

internal sealed class SwTimedItem
{
    public TimeSpan Duration { get; set; }

    public TimeSpan? Pause { get; set; }

    public TimeOnly Start { get; set; }

    public TimeOnly? End { get; set; }
}

/// <summary>Documents generated by <c>AddSwagger</c>, read with <see cref="ISwaggerProvider"/>.</summary>
public class SwashbuckleDocumentTests
{
    [Fact]
    public async Task Document_Should_KeepOnlyThePropertySummary_When_TheEnumTypeHasAnXmlSummary()
    {
        JsonNode document = await GetDocumentAsync(static app => app.MapPost("/review", static (SwReviewItem item) => item));

        JsonNode properties = document["components"]!["schemas"]![nameof(SwReviewItem)]!["properties"]!;
        string reference = $"#/components/schemas/{nameof(SwReviewState)}";

        properties["state"]!["description"]!.GetValue<string>().Should().Be("The current state.");
        properties["state"]!["allOf"]![0]!["$ref"]!.GetValue<string>().Should().Be(reference);

        properties["previous"]!["description"].Should().BeNull();
        properties["previous"]!["$ref"]!.GetValue<string>().Should().Be(reference);

        properties["next"]!["description"].Should().BeNull();
        properties["next"]!.ToJsonString().Should().Contain(reference).And.NotContain("The state of a review item.");

        document["components"]!["schemas"]![nameof(SwReviewState)]!["description"]!.GetValue<string>()
            .Should().StartWith("The state of a review item.");
    }

    [Fact]
    public async Task Document_Should_KeepNonNullableTimes_When_NullableTimesShareTheDocument()
    {
        JsonNode document = await GetDocumentAsync(static app => app.MapPost("/timed", static (SwTimedItem item) => item));

        JsonNode properties = document["components"]!["schemas"]![nameof(SwTimedItem)]!["properties"]!;

        foreach (string name in (string[])["duration", "start"])
        {
            properties[name]!["type"]!.GetValue<string>().Should().Be("string");
            properties[name]!["nullable"].Should().BeNull();
        }
        foreach (string name in (string[])["pause", "end"])
        {
            properties[name]!["type"]!.GetValue<string>().Should().Be("string");
            properties[name]!["nullable"]!.GetValue<bool>().Should().BeTrue();
        }
    }

    [Fact]
    public async Task Document_Should_RequireTheSecurityScheme_When_AddedByAddSwagger()
    {
        JsonNode document = await GetDocumentAsync(static app => app.MapGet("/ping", static () => "pong"));

        JsonArray security = document["security"]!.AsArray();
        security.Should().ContainSingle();
        security[0]!["Bearer"]!.AsArray().Should().BeEmpty();
        JsonNode scheme = document["components"]!["securitySchemes"]!["Bearer"]!;
        scheme["type"]!.GetValue<string>().Should().Be("http");
        scheme["scheme"]!.GetValue<string>().Should().Be("bearer");
    }

    [Fact]
    public async Task EnumOperationFilter_Should_HandleMissingCollections_When_EarlierFiltersClearThem()
    {
        await using WebApplication app = await StartAsync(
            static app => app.MapGet("/state/{state}", static (SwReviewState state) => state)
                .WithEnumWireFormat("X-Enum-Format", static _ => EnumWireFormat.Number),
            static options => options.OperationFilter<ClearCollectionsOperationFilter>());

        OpenApiDocument document = app.Services.GetRequiredService<ISwaggerProvider>().GetSwagger("v1");

        OpenApiOperation operation = document.Paths["/state/{state}"].Operations![HttpMethod.Get];
        operation.Parameters.Should().BeNull();
        operation.Responses.Should().BeNull();
        operation.Extensions.Should().ContainKey("x-enum-wire-format-header");
    }

    private static async Task<JsonNode> GetDocumentAsync(Action<WebApplication> map)
    {
        await using WebApplication app = await StartAsync(map);
        OpenApiDocument document = app.Services.GetRequiredService<ISwaggerProvider>().GetSwagger("v1");
        string json = await document.SerializeAsJsonAsync(OpenApiSpecVersion.OpenApi3_0);
        return JsonNode.Parse(json)!;
    }

    private static async Task<WebApplication> StartAsync(Action<WebApplication> map, Action<SwaggerGenOptions>? configure = null)
    {
        WebApplicationBuilder builder = WebApplication.CreateBuilder();
        builder.WebHost.UseTestServer();
        builder.Logging.ClearProviders();
        builder.Services.AddSwagger<DefaultConfigureSwaggerOptions>(
            "Bearer",
            new OpenApiSecurityScheme { Type = SecuritySchemeType.Http, Scheme = "bearer", BearerFormat = "JWT" },
            typeof(SwashbuckleDocumentTests).Assembly);
        if (configure is not null)
            builder.Services.Configure(configure);

        WebApplication app = builder.Build();
        map(app);
        await app.StartAsync();
        return app;
    }

    // Runs before the enum conventions (added in PostConfigure), so they see an operation without these collections.
    private sealed class ClearCollectionsOperationFilter : IOperationFilter
    {
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            operation.Parameters = null;
            operation.Responses = null;
            operation.Extensions = null;
        }
    }
}
