//HintName: Sample.PermissionsExtensions.g.cs
// <auto-generated/>
#nullable enable

namespace Sample
{
    /// <summary>Generated helpers for <see cref="global::Sample.Permissions"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("CSharpEssentials.Enums.Generators", "{version}")]
    internal static class PermissionsExtensions
    {
        public const string NoneSnakeCase = "none";
        public const string NoneKebabCase = "none";
        public const string NoneWireName = "none";
        public const string ReadSnakeCase = "read";
        public const string ReadKebabCase = "read";
        public const string ReadWireName = "read";
        public const string WriteSnakeCase = "write";
        public const string WriteKebabCase = "write";
        public const string WriteWireName = "write";
        public const string ReadWriteSnakeCase = "read_write";
        public const string ReadWriteKebabCase = "read-write";
        public const string ReadWriteWireName = "read_write";

        private static readonly global::CSharpEssentials.Enums.EnumConventions __WireReadConventions = global::CSharpEssentials.Enums.EnumConventions.Default with { UnknownValue = global::CSharpEssentials.Enums.UnknownEnumValueHandling.Reject };

        /// <summary>The canonical wire name. Throws <see cref="global::CSharpEssentials.Enums.EnumValueException"/> for undefined values.</summary>
        public static string ToWireName(this global::Sample.Permissions value)
        {
            return global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Permissions>().Format(value, global::CSharpEssentials.Enums.EnumWireFormat.String);
        }

        /// <summary>Parses with the data read rules (every known spelling, defined numbers), without the fallback member.</summary>
        public static bool TryParseWire(string? text, out global::Sample.Permissions value)
        {
            if (text is null)
            {
                value = default;
                return false;
            }

            return global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Permissions>().TryParse(text, global::CSharpEssentials.Enums.EnumReadMode.Data, __WireReadConventions, out value, out _);
        }

        /// <summary>Parses like <see cref="TryParseWire"/> and throws <see cref="global::CSharpEssentials.Enums.EnumValueException"/> on failure.</summary>
        public static global::Sample.Permissions ParseWire(string? text)
        {
            global::CSharpEssentials.Enums.EnumInfo<global::Sample.Permissions> info = global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Permissions>();
            if (text is null)
                throw new global::CSharpEssentials.Enums.EnumValueException(info.CreateError(null, global::CSharpEssentials.Enums.EnumReadMode.Data));
            if (info.TryParse(text, global::CSharpEssentials.Enums.EnumReadMode.Data, __WireReadConventions, out global::Sample.Permissions value, out global::CSharpEssentials.Enums.EnumValueError? error))
                return value;
            throw new global::CSharpEssentials.Enums.EnumValueException(error);
        }

        /// <summary>Whether <paramref name="value"/> is a defined member or a combination of defined flags.</summary>
        public static bool IsDefined(this global::Sample.Permissions value) => global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Permissions>().IsDefined(value);

        internal static global::CSharpEssentials.Enums.EnumInfo<global::Sample.Permissions> __CreateEnumInfo()
        {
            return new global::CSharpEssentials.Enums.EnumInfo<global::Sample.Permissions>(
                new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Permissions>[]
                {
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Permissions>(global::Sample.Permissions.None, 0UL, "None", NoneWireName),
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Permissions>(global::Sample.Permissions.Read, 1UL, "Read", ReadWireName),
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Permissions>(global::Sample.Permissions.Write, 2UL, "Write", WriteWireName),
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Permissions>(global::Sample.Permissions.ReadWrite, 3UL, "ReadWrite", ReadWriteWireName),
                },
                static v => unchecked((ulong)(long)v),
                static r => unchecked((global::Sample.Permissions)(long)r),
                true,
                (global::CSharpEssentials.Enums.EnumStorage)0);
        }

        public static string ToOptimizedString(this global::Sample.Permissions value)
        {
            switch (value)
            {
                case global::Sample.Permissions.None:
                    return "None";
                case global::Sample.Permissions.Read:
                    return "Read";
                case global::Sample.Permissions.Write:
                    return "Write";
                case global::Sample.Permissions.ReadWrite:
                    return "ReadWrite";
                default:
                    return value.ToString();
            }
        }

        [global::System.Obsolete("Use ToWireName()")]
        public static string ToSnakeCase(this global::Sample.Permissions value)
        {
            switch (value)
            {
                case global::Sample.Permissions.None:
                    return "none";
                case global::Sample.Permissions.Read:
                    return "read";
                case global::Sample.Permissions.Write:
                    return "write";
                case global::Sample.Permissions.ReadWrite:
                    return "read_write";
                default:
                    return ToSnakeCaseFallback(value.ToOptimizedString());
            }
        }

        public static string ToKebabCase(this global::Sample.Permissions value)
        {
            switch (value)
            {
                case global::Sample.Permissions.None:
                    return "none";
                case global::Sample.Permissions.Read:
                    return "read";
                case global::Sample.Permissions.Write:
                    return "write";
                case global::Sample.Permissions.ReadWrite:
                    return "read-write";
                default:
                    return ToKebabCaseFallback(value.ToOptimizedString());
            }
        }

        public static string ToLowerCase(this global::Sample.Permissions value)
        {
            switch (value)
            {
                case global::Sample.Permissions.None:
                    return "None".ToLowerInvariant();
                case global::Sample.Permissions.Read:
                    return "Read".ToLowerInvariant();
                case global::Sample.Permissions.Write:
                    return "Write".ToLowerInvariant();
                case global::Sample.Permissions.ReadWrite:
                    return "ReadWrite".ToLowerInvariant();
                default:
                    return value.ToString().ToLowerInvariant();
            }
        }

        public static string ToUpperCase(this global::Sample.Permissions value)
        {
            switch (value)
            {
                case global::Sample.Permissions.None:
                    return "None".ToUpperInvariant();
                case global::Sample.Permissions.Read:
                    return "Read".ToUpperInvariant();
                case global::Sample.Permissions.Write:
                    return "Write".ToUpperInvariant();
                case global::Sample.Permissions.ReadWrite:
                    return "ReadWrite".ToUpperInvariant();
                default:
                    return value.ToString().ToUpperInvariant();
            }
        }

        public static bool IsDefined(string name)
        {
            switch (name)
            {
                case "None":
                case "Read":
                case "Write":
                case "ReadWrite":
                    return true;
                default:
                    return false;
            }
        }

        [global::System.Obsolete("Use TryParseWire/ParseWire")]
        public static bool TryParse(string? name, out global::Sample.Permissions value)
        {
            switch (name)
            {
                case "None":
                    value = global::Sample.Permissions.None;
                    return true;
                case "Read":
                    value = global::Sample.Permissions.Read;
                    return true;
                case "Write":
                    value = global::Sample.Permissions.Write;
                    return true;
                case "ReadWrite":
                    value = global::Sample.Permissions.ReadWrite;
                    return true;
            }

            byte numericValue;
            if (name != null && byte.TryParse(name, out numericValue))
            {
                value = (global::Sample.Permissions)numericValue;
                return true;
            }

            value = (global::Sample.Permissions)0;
            return false;
        }

        [global::System.Obsolete("Use TryParseWire/ParseWire")]
        public static global::Sample.Permissions Parse(string? name)
        {
            global::Sample.Permissions value;
            if (TryParse(name, out value))
            {
                return value;
            }

            throw new global::System.ArgumentException("Requested value '" + name + "' was not found.");
        }

        public static string[] GetNames()
        {
            return new string[] { "None", "Read", "Write", "ReadWrite" };
        }

        public static global::Sample.Permissions[] GetValues()
        {
            return new global::Sample.Permissions[] { global::Sample.Permissions.None, global::Sample.Permissions.Read, global::Sample.Permissions.Write, global::Sample.Permissions.ReadWrite };
        }

        public static byte AsUnderlyingType(this global::Sample.Permissions value)
        {
            return (byte)value;
        }

        private static string ToSnakeCaseFallback(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length + 4);
            global::System.Globalization.UnicodeCategory previous = global::System.Globalization.UnicodeCategory.OtherSymbol;
            bool isFirst = true;
            for (int i = 0; i < input.Length; i++)
            {
                char c = input[i];
                global::System.Globalization.UnicodeCategory current = char.GetUnicodeCategory(c);
                bool insertSeparator = CheckCategory(previous, current);
                bool isSpecial = IsSpecialCharacter(current);
                if (!isSpecial)
                {
                    if (insertSeparator && !isFirst) sb.Append('_');
                    sb.Append(char.ToLowerInvariant(c));
                    isFirst = false;
                }
                previous = current;
            }
            return sb.ToString();
        }

        private static string ToKebabCaseFallback(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length + 4);
            global::System.Globalization.UnicodeCategory previous = global::System.Globalization.UnicodeCategory.OtherSymbol;
            bool isFirst = true;
            for (int i = 0; i < input.Length; i++)
            {
                char c = input[i];
                global::System.Globalization.UnicodeCategory current = char.GetUnicodeCategory(c);
                bool insertSeparator = CheckCategory(previous, current);
                bool isSpecial = IsSpecialCharacter(current);
                if (!isSpecial)
                {
                    if (insertSeparator && !isFirst) sb.Append('-');
                    sb.Append(char.ToLowerInvariant(c));
                    isFirst = false;
                }
                previous = current;
            }
            return sb.ToString();
        }

        private static bool CheckCategory(global::System.Globalization.UnicodeCategory previous, global::System.Globalization.UnicodeCategory current)
        {
            return previous != current && (current == global::System.Globalization.UnicodeCategory.UppercaseLetter || current == global::System.Globalization.UnicodeCategory.DecimalDigitNumber || IsSpecialCharacter(previous) && !IsSpecialCharacter(current));
        }

        private static bool IsSpecialCharacter(global::System.Globalization.UnicodeCategory category)
        {
            return category != global::System.Globalization.UnicodeCategory.UppercaseLetter
                && category != global::System.Globalization.UnicodeCategory.LowercaseLetter
                && category != global::System.Globalization.UnicodeCategory.DecimalDigitNumber;
        }
    }
}
