//HintName: Sample.OrderStatusExtensions.g.cs
// <auto-generated/>
#nullable enable

namespace Sample
{
    /// <summary>Generated helpers for <see cref="global::Sample.OrderStatus"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("CSharpEssentials.Enums.Generators", "{version}")]
    public static class OrderStatusExtensions
    {
        public const string PendingSnakeCase = "pending";
        public const string PendingKebabCase = "pending";
        public const string PendingWireName = "pending";
        public const string InProgressSnakeCase = "in_progress";
        public const string InProgressKebabCase = "in-progress";
        public const string InProgressWireName = "in_progress";
        public const string ShippedSnakeCase = "shipped";
        public const string ShippedKebabCase = "shipped";
        public const string ShippedWireName = "shipped";

        private static readonly global::CSharpEssentials.Enums.EnumConventions __WireReadConventions = global::CSharpEssentials.Enums.EnumConventions.Default with { UnknownValue = global::CSharpEssentials.Enums.UnknownEnumValueHandling.Reject };

        /// <summary>The canonical wire name. Throws <see cref="global::CSharpEssentials.Enums.EnumValueException"/> for undefined values.</summary>
        public static string ToWireName(this global::Sample.OrderStatus value)
        {
            switch (value)
            {
                case global::Sample.OrderStatus.Pending:
                    return PendingWireName;
                case global::Sample.OrderStatus.InProgress:
                    return InProgressWireName;
                case global::Sample.OrderStatus.Shipped:
                    return ShippedWireName;
                default:
                    return global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.OrderStatus>().Format(value, global::CSharpEssentials.Enums.EnumWireFormat.String);
            }
        }

        /// <summary>Parses with the data read rules (every known spelling, defined numbers), without the fallback member.</summary>
        public static bool TryParseWire(string? text, out global::Sample.OrderStatus value)
        {
            if (text is null)
            {
                value = default;
                return false;
            }

            return global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.OrderStatus>().TryParse(text, global::CSharpEssentials.Enums.EnumReadMode.Data, __WireReadConventions, out value, out _);
        }

        /// <summary>Parses like <see cref="TryParseWire"/> and throws <see cref="global::CSharpEssentials.Enums.EnumValueException"/> on failure.</summary>
        public static global::Sample.OrderStatus ParseWire(string? text)
        {
            global::CSharpEssentials.Enums.EnumInfo<global::Sample.OrderStatus> info = global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.OrderStatus>();
            if (text is null)
                throw new global::CSharpEssentials.Enums.EnumValueException(info.CreateError(null, global::CSharpEssentials.Enums.EnumReadMode.Data));
            if (info.TryParse(text, global::CSharpEssentials.Enums.EnumReadMode.Data, __WireReadConventions, out global::Sample.OrderStatus value, out global::CSharpEssentials.Enums.EnumValueError? error))
                return value;
            throw new global::CSharpEssentials.Enums.EnumValueException(error);
        }

        /// <summary>Whether <paramref name="value"/> is a defined member.</summary>
        public static bool IsDefined(this global::Sample.OrderStatus value) => global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.OrderStatus>().IsDefined(value);

        internal static global::CSharpEssentials.Enums.EnumInfo<global::Sample.OrderStatus> __CreateEnumInfo()
        {
            return new global::CSharpEssentials.Enums.EnumInfo<global::Sample.OrderStatus>(
                new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.OrderStatus>[]
                {
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.OrderStatus>(global::Sample.OrderStatus.Pending, 0UL, "Pending", PendingWireName),
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.OrderStatus>(global::Sample.OrderStatus.InProgress, 1UL, "InProgress", InProgressWireName),
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.OrderStatus>(global::Sample.OrderStatus.Shipped, 2UL, "Shipped", ShippedWireName),
                },
                static v => unchecked((ulong)(long)v),
                static r => unchecked((global::Sample.OrderStatus)(long)r),
                false,
                (global::CSharpEssentials.Enums.EnumStorage)0);
        }

        public static string ToOptimizedString(this global::Sample.OrderStatus value)
        {
            switch (value)
            {
                case global::Sample.OrderStatus.Pending:
                    return "Pending";
                case global::Sample.OrderStatus.InProgress:
                    return "InProgress";
                case global::Sample.OrderStatus.Shipped:
                    return "Shipped";
                default:
                    return value.ToString();
            }
        }

        [global::System.Obsolete("Use ToWireName()")]
        public static string ToSnakeCase(this global::Sample.OrderStatus value)
        {
            switch (value)
            {
                case global::Sample.OrderStatus.Pending:
                    return "pending";
                case global::Sample.OrderStatus.InProgress:
                    return "in_progress";
                case global::Sample.OrderStatus.Shipped:
                    return "shipped";
                default:
                    return ToSnakeCaseFallback(value.ToOptimizedString());
            }
        }

        public static string ToKebabCase(this global::Sample.OrderStatus value)
        {
            switch (value)
            {
                case global::Sample.OrderStatus.Pending:
                    return "pending";
                case global::Sample.OrderStatus.InProgress:
                    return "in-progress";
                case global::Sample.OrderStatus.Shipped:
                    return "shipped";
                default:
                    return ToKebabCaseFallback(value.ToOptimizedString());
            }
        }

        public static string ToLowerCase(this global::Sample.OrderStatus value)
        {
            switch (value)
            {
                case global::Sample.OrderStatus.Pending:
                    return "Pending".ToLowerInvariant();
                case global::Sample.OrderStatus.InProgress:
                    return "InProgress".ToLowerInvariant();
                case global::Sample.OrderStatus.Shipped:
                    return "Shipped".ToLowerInvariant();
                default:
                    return value.ToString().ToLowerInvariant();
            }
        }

        public static string ToUpperCase(this global::Sample.OrderStatus value)
        {
            switch (value)
            {
                case global::Sample.OrderStatus.Pending:
                    return "Pending".ToUpperInvariant();
                case global::Sample.OrderStatus.InProgress:
                    return "InProgress".ToUpperInvariant();
                case global::Sample.OrderStatus.Shipped:
                    return "Shipped".ToUpperInvariant();
                default:
                    return value.ToString().ToUpperInvariant();
            }
        }

        public static bool IsDefined(string name)
        {
            switch (name)
            {
                case "Pending":
                case "InProgress":
                case "Shipped":
                    return true;
                default:
                    return false;
            }
        }

        [global::System.Obsolete("Use TryParseWire/ParseWire")]
        public static bool TryParse(string? name, out global::Sample.OrderStatus value)
        {
            switch (name)
            {
                case "Pending":
                    value = global::Sample.OrderStatus.Pending;
                    return true;
                case "InProgress":
                    value = global::Sample.OrderStatus.InProgress;
                    return true;
                case "Shipped":
                    value = global::Sample.OrderStatus.Shipped;
                    return true;
            }

            int numericValue;
            if (name != null && int.TryParse(name, out numericValue))
            {
                value = (global::Sample.OrderStatus)numericValue;
                return true;
            }

            value = (global::Sample.OrderStatus)0;
            return false;
        }

        [global::System.Obsolete("Use TryParseWire/ParseWire")]
        public static global::Sample.OrderStatus Parse(string? name)
        {
            global::Sample.OrderStatus value;
            if (TryParse(name, out value))
            {
                return value;
            }

            throw new global::System.ArgumentException("Requested value '" + name + "' was not found.");
        }

        public static string[] GetNames()
        {
            return new string[] { "Pending", "InProgress", "Shipped" };
        }

        public static global::Sample.OrderStatus[] GetValues()
        {
            return new global::Sample.OrderStatus[] { global::Sample.OrderStatus.Pending, global::Sample.OrderStatus.InProgress, global::Sample.OrderStatus.Shipped };
        }

        public static int AsUnderlyingType(this global::Sample.OrderStatus value)
        {
            return (int)value;
        }

        private static string ToSnakeCaseFallback(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length + 4);
            global::System.Globalization.UnicodeCategory previous = global::System.Globalization.UnicodeCategory.OtherSymbol;
            bool isFirst = true;
            for (int i = 0; i < input.Length; i++)
            {
                char c = input[i];
                global::System.Globalization.UnicodeCategory current = char.GetUnicodeCategory(c);
                bool insertSeparator = CheckCategory(previous, current);
                bool isSpecial = IsSpecialCharacter(current);
                if (!isSpecial)
                {
                    if (insertSeparator && !isFirst) sb.Append('_');
                    sb.Append(char.ToLowerInvariant(c));
                    isFirst = false;
                }
                previous = current;
            }
            return sb.ToString();
        }

        private static string ToKebabCaseFallback(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length + 4);
            global::System.Globalization.UnicodeCategory previous = global::System.Globalization.UnicodeCategory.OtherSymbol;
            bool isFirst = true;
            for (int i = 0; i < input.Length; i++)
            {
                char c = input[i];
                global::System.Globalization.UnicodeCategory current = char.GetUnicodeCategory(c);
                bool insertSeparator = CheckCategory(previous, current);
                bool isSpecial = IsSpecialCharacter(current);
                if (!isSpecial)
                {
                    if (insertSeparator && !isFirst) sb.Append('-');
                    sb.Append(char.ToLowerInvariant(c));
                    isFirst = false;
                }
                previous = current;
            }
            return sb.ToString();
        }

        private static bool CheckCategory(global::System.Globalization.UnicodeCategory previous, global::System.Globalization.UnicodeCategory current)
        {
            return previous != current && (current == global::System.Globalization.UnicodeCategory.UppercaseLetter || current == global::System.Globalization.UnicodeCategory.DecimalDigitNumber || IsSpecialCharacter(previous) && !IsSpecialCharacter(current));
        }

        private static bool IsSpecialCharacter(global::System.Globalization.UnicodeCategory category)
        {
            return category != global::System.Globalization.UnicodeCategory.UppercaseLetter
                && category != global::System.Globalization.UnicodeCategory.LowercaseLetter
                && category != global::System.Globalization.UnicodeCategory.DecimalDigitNumber;
        }
    }
}
