//HintName: Sample.HugeExtensions.g.cs
// <auto-generated/>
#nullable enable

namespace Sample
{
    /// <summary>Generated helpers for <see cref="global::Sample.Huge"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("CSharpEssentials.Enums.Generators", "{version}")]
    public static class HugeExtensions
    {
        public const string ZeroSnakeCase = "zero";
        public const string ZeroKebabCase = "zero";
        public const string ZeroWireName = "zero";
        public const string MaxSnakeCase = "max";
        public const string MaxKebabCase = "max";
        public const string MaxWireName = "max";

        private static readonly global::CSharpEssentials.Enums.EnumConventions __WireReadConventions = global::CSharpEssentials.Enums.EnumConventions.Default with { UnknownValue = global::CSharpEssentials.Enums.UnknownEnumValueHandling.Reject };

        /// <summary>The canonical wire name. Throws <see cref="global::CSharpEssentials.Enums.EnumValueException"/> for undefined values.</summary>
        public static string ToWireName(this global::Sample.Huge value)
        {
            switch (value)
            {
                case global::Sample.Huge.Zero:
                    return ZeroWireName;
                case (global::Sample.Huge)18446744073709551615UL:
                    return MaxWireName;
                default:
                    return global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Huge>().Format(value, global::CSharpEssentials.Enums.EnumWireFormat.String);
            }
        }

        /// <summary>Parses with the data read rules (every known spelling, defined numbers), without the fallback member.</summary>
        public static bool TryParseWire(string? text, out global::Sample.Huge value)
        {
            if (text is null)
            {
                value = default;
                return false;
            }

            return global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Huge>().TryParse(text, global::CSharpEssentials.Enums.EnumReadMode.Data, __WireReadConventions, out value, out _);
        }

        /// <summary>Parses like <see cref="TryParseWire"/> and throws <see cref="global::CSharpEssentials.Enums.EnumValueException"/> on failure.</summary>
        public static global::Sample.Huge ParseWire(string? text)
        {
            global::CSharpEssentials.Enums.EnumInfo<global::Sample.Huge> info = global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Huge>();
            if (text is null)
                throw new global::CSharpEssentials.Enums.EnumValueException(info.CreateError(null, global::CSharpEssentials.Enums.EnumReadMode.Data));
            if (info.TryParse(text, global::CSharpEssentials.Enums.EnumReadMode.Data, __WireReadConventions, out global::Sample.Huge value, out global::CSharpEssentials.Enums.EnumValueError? error))
                return value;
            throw new global::CSharpEssentials.Enums.EnumValueException(error);
        }

        /// <summary>Whether <paramref name="value"/> is a defined member.</summary>
        public static bool IsDefined(this global::Sample.Huge value) => global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Huge>().IsDefined(value);

        internal static global::CSharpEssentials.Enums.EnumInfo<global::Sample.Huge> __CreateEnumInfo()
        {
            return new global::CSharpEssentials.Enums.EnumInfo<global::Sample.Huge>(
                new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Huge>[]
                {
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Huge>(global::Sample.Huge.Zero, 0UL, "Zero", ZeroWireName),
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Huge>((global::Sample.Huge)18446744073709551615UL, 18446744073709551615UL, "Max", MaxWireName) { IsObsolete = true },
                },
                static v => unchecked((ulong)(long)v),
                static r => unchecked((global::Sample.Huge)(long)r),
                false,
                (global::CSharpEssentials.Enums.EnumStorage)0);
        }

        public static string ToOptimizedString(this global::Sample.Huge value)
        {
            switch (value)
            {
                case global::Sample.Huge.Zero:
                    return "Zero";
                case (global::Sample.Huge)18446744073709551615UL:
                    return "Max";
                default:
                    return value.ToString();
            }
        }

        [global::System.Obsolete("Use ToWireName()")]
        public static string ToSnakeCase(this global::Sample.Huge value)
        {
            switch (value)
            {
                case global::Sample.Huge.Zero:
                    return "zero";
                case (global::Sample.Huge)18446744073709551615UL:
                    return "max";
                default:
                    return ToSnakeCaseFallback(value.ToOptimizedString());
            }
        }

        public static string ToKebabCase(this global::Sample.Huge value)
        {
            switch (value)
            {
                case global::Sample.Huge.Zero:
                    return "zero";
                case (global::Sample.Huge)18446744073709551615UL:
                    return "max";
                default:
                    return ToKebabCaseFallback(value.ToOptimizedString());
            }
        }

        public static string ToLowerCase(this global::Sample.Huge value)
        {
            switch (value)
            {
                case global::Sample.Huge.Zero:
                    return "Zero".ToLowerInvariant();
                case (global::Sample.Huge)18446744073709551615UL:
                    return "Max".ToLowerInvariant();
                default:
                    return value.ToString().ToLowerInvariant();
            }
        }

        public static string ToUpperCase(this global::Sample.Huge value)
        {
            switch (value)
            {
                case global::Sample.Huge.Zero:
                    return "Zero".ToUpperInvariant();
                case (global::Sample.Huge)18446744073709551615UL:
                    return "Max".ToUpperInvariant();
                default:
                    return value.ToString().ToUpperInvariant();
            }
        }

        public static bool IsDefined(string name)
        {
            switch (name)
            {
                case "Zero":
                case "Max":
                    return true;
                default:
                    return false;
            }
        }

        [global::System.Obsolete("Use TryParseWire/ParseWire")]
        public static bool TryParse(string? name, out global::Sample.Huge value)
        {
            switch (name)
            {
                case "Zero":
                    value = global::Sample.Huge.Zero;
                    return true;
                case "Max":
                    value = (global::Sample.Huge)18446744073709551615UL;
                    return true;
            }

            ulong numericValue;
            if (name != null && ulong.TryParse(name, out numericValue))
            {
                value = (global::Sample.Huge)numericValue;
                return true;
            }

            value = (global::Sample.Huge)0;
            return false;
        }

        [global::System.Obsolete("Use TryParseWire/ParseWire")]
        public static global::Sample.Huge Parse(string? name)
        {
            global::Sample.Huge value;
            if (TryParse(name, out value))
            {
                return value;
            }

            throw new global::System.ArgumentException("Requested value '" + name + "' was not found.");
        }

        public static string[] GetNames()
        {
            return new string[] { "Zero", "Max" };
        }

        public static global::Sample.Huge[] GetValues()
        {
            return new global::Sample.Huge[] { global::Sample.Huge.Zero, (global::Sample.Huge)18446744073709551615UL };
        }

        public static ulong AsUnderlyingType(this global::Sample.Huge value)
        {
            return (ulong)value;
        }

        private static string ToSnakeCaseFallback(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length + 4);
            global::System.Globalization.UnicodeCategory previous = global::System.Globalization.UnicodeCategory.OtherSymbol;
            bool isFirst = true;
            for (int i = 0; i < input.Length; i++)
            {
                char c = input[i];
                global::System.Globalization.UnicodeCategory current = char.GetUnicodeCategory(c);
                bool insertSeparator = CheckCategory(previous, current);
                bool isSpecial = IsSpecialCharacter(current);
                if (!isSpecial)
                {
                    if (insertSeparator && !isFirst) sb.Append('_');
                    sb.Append(char.ToLowerInvariant(c));
                    isFirst = false;
                }
                previous = current;
            }
            return sb.ToString();
        }

        private static string ToKebabCaseFallback(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length + 4);
            global::System.Globalization.UnicodeCategory previous = global::System.Globalization.UnicodeCategory.OtherSymbol;
            bool isFirst = true;
            for (int i = 0; i < input.Length; i++)
            {
                char c = input[i];
                global::System.Globalization.UnicodeCategory current = char.GetUnicodeCategory(c);
                bool insertSeparator = CheckCategory(previous, current);
                bool isSpecial = IsSpecialCharacter(current);
                if (!isSpecial)
                {
                    if (insertSeparator && !isFirst) sb.Append('-');
                    sb.Append(char.ToLowerInvariant(c));
                    isFirst = false;
                }
                previous = current;
            }
            return sb.ToString();
        }

        private static bool CheckCategory(global::System.Globalization.UnicodeCategory previous, global::System.Globalization.UnicodeCategory current)
        {
            return previous != current && (current == global::System.Globalization.UnicodeCategory.UppercaseLetter || current == global::System.Globalization.UnicodeCategory.DecimalDigitNumber || IsSpecialCharacter(previous) && !IsSpecialCharacter(current));
        }

        private static bool IsSpecialCharacter(global::System.Globalization.UnicodeCategory category)
        {
            return category != global::System.Globalization.UnicodeCategory.UppercaseLetter
                && category != global::System.Globalization.UnicodeCategory.LowercaseLetter
                && category != global::System.Globalization.UnicodeCategory.DecimalDigitNumber;
        }
    }
}
