//HintName: Sample.Order+StateExtensions.g.cs
// <auto-generated/>
#nullable enable

namespace Sample
{
    /// <summary>Generated helpers for <see cref="global::Sample.Order.State"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("CSharpEssentials.Enums.Generators", "{version}")]
    public static class Order_StateExtensions
    {
        public const string OpenSnakeCase = "open";
        public const string OpenKebabCase = "open";
        public const string OpenWireName = "open";
        public const string ClosedSnakeCase = "closed";
        public const string ClosedKebabCase = "closed";
        public const string ClosedWireName = "closed";

        private static readonly global::CSharpEssentials.Enums.EnumConventions __WireReadConventions = global::CSharpEssentials.Enums.EnumConventions.Default with { UnknownValue = global::CSharpEssentials.Enums.UnknownEnumValueHandling.Reject };

        /// <summary>The canonical wire name. Throws <see cref="global::CSharpEssentials.Enums.EnumValueException"/> for undefined values.</summary>
        public static string ToWireName(this global::Sample.Order.State value)
        {
            switch (value)
            {
                case global::Sample.Order.State.Open:
                    return OpenWireName;
                case global::Sample.Order.State.Closed:
                    return ClosedWireName;
                default:
                    return global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Order.State>().Format(value, global::CSharpEssentials.Enums.EnumWireFormat.String);
            }
        }

        /// <summary>Parses with the data read rules (every known spelling, defined numbers), without the fallback member.</summary>
        public static bool TryParseWire(string? text, out global::Sample.Order.State value)
        {
            if (text is null)
            {
                value = default;
                return false;
            }

            return global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Order.State>().TryParse(text, global::CSharpEssentials.Enums.EnumReadMode.Data, __WireReadConventions, out value, out _);
        }

        /// <summary>Parses like <see cref="TryParseWire"/> and throws <see cref="global::CSharpEssentials.Enums.EnumValueException"/> on failure.</summary>
        public static global::Sample.Order.State ParseWire(string? text)
        {
            global::CSharpEssentials.Enums.EnumInfo<global::Sample.Order.State> info = global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Order.State>();
            if (text is null)
                throw new global::CSharpEssentials.Enums.EnumValueException(info.CreateError(null, global::CSharpEssentials.Enums.EnumReadMode.Data));
            if (info.TryParse(text, global::CSharpEssentials.Enums.EnumReadMode.Data, __WireReadConventions, out global::Sample.Order.State value, out global::CSharpEssentials.Enums.EnumValueError? error))
                return value;
            throw new global::CSharpEssentials.Enums.EnumValueException(error);
        }

        /// <summary>Whether <paramref name="value"/> is a defined member.</summary>
        public static bool IsDefined(this global::Sample.Order.State value) => global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Order.State>().IsDefined(value);

        internal static global::CSharpEssentials.Enums.EnumInfo<global::Sample.Order.State> __CreateEnumInfo()
        {
            return new global::CSharpEssentials.Enums.EnumInfo<global::Sample.Order.State>(
                new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Order.State>[]
                {
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Order.State>(global::Sample.Order.State.Open, 0UL, "Open", OpenWireName),
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Order.State>(global::Sample.Order.State.Closed, 1UL, "Closed", ClosedWireName),
                },
                static v => unchecked((ulong)(long)v),
                static r => unchecked((global::Sample.Order.State)(long)r),
                false,
                (global::CSharpEssentials.Enums.EnumStorage)0);
        }

        public static string ToOptimizedString(this global::Sample.Order.State value)
        {
            switch (value)
            {
                case global::Sample.Order.State.Open:
                    return "Open";
                case global::Sample.Order.State.Closed:
                    return "Closed";
                default:
                    return value.ToString();
            }
        }

        [global::System.Obsolete("Use ToWireName()")]
        public static string ToSnakeCase(this global::Sample.Order.State value)
        {
            switch (value)
            {
                case global::Sample.Order.State.Open:
                    return "open";
                case global::Sample.Order.State.Closed:
                    return "closed";
                default:
                    return ToSnakeCaseFallback(value.ToOptimizedString());
            }
        }

        public static string ToKebabCase(this global::Sample.Order.State value)
        {
            switch (value)
            {
                case global::Sample.Order.State.Open:
                    return "open";
                case global::Sample.Order.State.Closed:
                    return "closed";
                default:
                    return ToKebabCaseFallback(value.ToOptimizedString());
            }
        }

        public static string ToLowerCase(this global::Sample.Order.State value)
        {
            switch (value)
            {
                case global::Sample.Order.State.Open:
                    return "Open".ToLowerInvariant();
                case global::Sample.Order.State.Closed:
                    return "Closed".ToLowerInvariant();
                default:
                    return value.ToString().ToLowerInvariant();
            }
        }

        public static string ToUpperCase(this global::Sample.Order.State value)
        {
            switch (value)
            {
                case global::Sample.Order.State.Open:
                    return "Open".ToUpperInvariant();
                case global::Sample.Order.State.Closed:
                    return "Closed".ToUpperInvariant();
                default:
                    return value.ToString().ToUpperInvariant();
            }
        }

        public static bool IsDefined(string name)
        {
            switch (name)
            {
                case "Open":
                case "Closed":
                    return true;
                default:
                    return false;
            }
        }

        [global::System.Obsolete("Use TryParseWire/ParseWire")]
        public static bool TryParse(string? name, out global::Sample.Order.State value)
        {
            switch (name)
            {
                case "Open":
                    value = global::Sample.Order.State.Open;
                    return true;
                case "Closed":
                    value = global::Sample.Order.State.Closed;
                    return true;
            }

            int numericValue;
            if (name != null && int.TryParse(name, out numericValue))
            {
                value = (global::Sample.Order.State)numericValue;
                return true;
            }

            value = (global::Sample.Order.State)0;
            return false;
        }

        [global::System.Obsolete("Use TryParseWire/ParseWire")]
        public static global::Sample.Order.State Parse(string? name)
        {
            global::Sample.Order.State value;
            if (TryParse(name, out value))
            {
                return value;
            }

            throw new global::System.ArgumentException("Requested value '" + name + "' was not found.");
        }

        public static string[] GetNames()
        {
            return new string[] { "Open", "Closed" };
        }

        public static global::Sample.Order.State[] GetValues()
        {
            return new global::Sample.Order.State[] { global::Sample.Order.State.Open, global::Sample.Order.State.Closed };
        }

        public static int AsUnderlyingType(this global::Sample.Order.State value)
        {
            return (int)value;
        }

        private static string ToSnakeCaseFallback(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length + 4);
            global::System.Globalization.UnicodeCategory previous = global::System.Globalization.UnicodeCategory.OtherSymbol;
            bool isFirst = true;
            for (int i = 0; i < input.Length; i++)
            {
                char c = input[i];
                global::System.Globalization.UnicodeCategory current = char.GetUnicodeCategory(c);
                bool insertSeparator = CheckCategory(previous, current);
                bool isSpecial = IsSpecialCharacter(current);
                if (!isSpecial)
                {
                    if (insertSeparator && !isFirst) sb.Append('_');
                    sb.Append(char.ToLowerInvariant(c));
                    isFirst = false;
                }
                previous = current;
            }
            return sb.ToString();
        }

        private static string ToKebabCaseFallback(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length + 4);
            global::System.Globalization.UnicodeCategory previous = global::System.Globalization.UnicodeCategory.OtherSymbol;
            bool isFirst = true;
            for (int i = 0; i < input.Length; i++)
            {
                char c = input[i];
                global::System.Globalization.UnicodeCategory current = char.GetUnicodeCategory(c);
                bool insertSeparator = CheckCategory(previous, current);
                bool isSpecial = IsSpecialCharacter(current);
                if (!isSpecial)
                {
                    if (insertSeparator && !isFirst) sb.Append('-');
                    sb.Append(char.ToLowerInvariant(c));
                    isFirst = false;
                }
                previous = current;
            }
            return sb.ToString();
        }

        private static bool CheckCategory(global::System.Globalization.UnicodeCategory previous, global::System.Globalization.UnicodeCategory current)
        {
            return previous != current && (current == global::System.Globalization.UnicodeCategory.UppercaseLetter || current == global::System.Globalization.UnicodeCategory.DecimalDigitNumber || IsSpecialCharacter(previous) && !IsSpecialCharacter(current));
        }

        private static bool IsSpecialCharacter(global::System.Globalization.UnicodeCategory category)
        {
            return category != global::System.Globalization.UnicodeCategory.UppercaseLetter
                && category != global::System.Globalization.UnicodeCategory.LowercaseLetter
                && category != global::System.Globalization.UnicodeCategory.DecimalDigitNumber;
        }
    }
}
