//HintName: __CSharpEssentialsEnumRegistry.g.cs
// <auto-generated/>
#nullable enable

/// <summary>Registers the generated enum metadata of this assembly.</summary>
[global::System.CodeDom.Compiler.GeneratedCode("CSharpEssentials.Enums.Generators", "{version}")]
internal static class __CSharpEssentialsEnumRegistry
{
    /// <summary>Registers every <c>[StringEnum]</c> enum of this assembly in <see cref="global::CSharpEssentials.Enums.EnumMetadata"/>.</summary>
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register()
    {
        global::CSharpEssentials.Enums.EnumMetadata.Register(global::Sample.OrderStatusExtensions.__CreateEnumInfo());
    }
}
