//HintName: Sample.Order_Line_KindExtensions.g.cs
// <auto-generated/>
#nullable enable

namespace Sample
{
    /// <summary>Generated helpers for <see cref="global::Sample.Order.Line.Kind"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("CSharpEssentials.Enums.Generators", "{version}")]
    internal static class Order_Line_KindExtensions
    {
        public const string ProductSnakeCase = "product";
        public const string ProductKebabCase = "product";
        public const string ProductWireName = "product";
        public const string ShippingSnakeCase = "shipping";
        public const string ShippingKebabCase = "shipping";
        public const string ShippingWireName = "shipping";

        private static readonly global::CSharpEssentials.Enums.EnumConventions __WireReadConventions = global::CSharpEssentials.Enums.EnumConventions.Default with { UnknownValue = global::CSharpEssentials.Enums.UnknownEnumValueHandling.Reject };

        /// <summary>The canonical wire name. Throws <see cref="global::CSharpEssentials.Enums.EnumValueException"/> for undefined values.</summary>
        public static string ToWireName(this global::Sample.Order.Line.Kind value)
        {
            switch (value)
            {
                case global::Sample.Order.Line.Kind.Product:
                    return ProductWireName;
                case global::Sample.Order.Line.Kind.Shipping:
                    return ShippingWireName;
                default:
                    return global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Order.Line.Kind>().Format(value, global::CSharpEssentials.Enums.EnumWireFormat.String);
            }
        }

        /// <summary>Parses with the data read rules (every known spelling, defined numbers), without the fallback member.</summary>
        public static bool TryParseWire(string? text, out global::Sample.Order.Line.Kind value)
        {
            if (text is null)
            {
                value = default;
                return false;
            }

            return global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Order.Line.Kind>().TryParse(text, global::CSharpEssentials.Enums.EnumReadMode.Data, __WireReadConventions, out value, out _);
        }

        /// <summary>Parses like <see cref="TryParseWire"/> and throws <see cref="global::CSharpEssentials.Enums.EnumValueException"/> on failure.</summary>
        public static global::Sample.Order.Line.Kind ParseWire(string? text)
        {
            global::CSharpEssentials.Enums.EnumInfo<global::Sample.Order.Line.Kind> info = global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Order.Line.Kind>();
            if (text is null)
                throw new global::CSharpEssentials.Enums.EnumValueException(info.CreateError(null, global::CSharpEssentials.Enums.EnumReadMode.Data));
            if (info.TryParse(text, global::CSharpEssentials.Enums.EnumReadMode.Data, __WireReadConventions, out global::Sample.Order.Line.Kind value, out global::CSharpEssentials.Enums.EnumValueError? error))
                return value;
            throw new global::CSharpEssentials.Enums.EnumValueException(error);
        }

        /// <summary>Whether <paramref name="value"/> is a defined member.</summary>
        public static bool IsDefined(this global::Sample.Order.Line.Kind value) => global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Order.Line.Kind>().IsDefined(value);

        internal static global::CSharpEssentials.Enums.EnumInfo<global::Sample.Order.Line.Kind> __CreateEnumInfo()
        {
            return new global::CSharpEssentials.Enums.EnumInfo<global::Sample.Order.Line.Kind>(
                new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Order.Line.Kind>[]
                {
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Order.Line.Kind>(global::Sample.Order.Line.Kind.Product, 0UL, "Product", ProductWireName),
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Order.Line.Kind>(global::Sample.Order.Line.Kind.Shipping, 1UL, "Shipping", ShippingWireName),
                },
                static v => unchecked((ulong)(long)v),
                static r => unchecked((global::Sample.Order.Line.Kind)(long)r),
                false,
                (global::CSharpEssentials.Enums.EnumStorage)0);
        }

        public static string ToOptimizedString(this global::Sample.Order.Line.Kind value)
        {
            switch (value)
            {
                case global::Sample.Order.Line.Kind.Product:
                    return "Product";
                case global::Sample.Order.Line.Kind.Shipping:
                    return "Shipping";
                default:
                    return value.ToString();
            }
        }

        [global::System.Obsolete("Use ToWireName()")]
        public static string ToSnakeCase(this global::Sample.Order.Line.Kind value)
        {
            switch (value)
            {
                case global::Sample.Order.Line.Kind.Product:
                    return "product";
                case global::Sample.Order.Line.Kind.Shipping:
                    return "shipping";
                default:
                    return ToSnakeCaseFallback(value.ToOptimizedString());
            }
        }

        public static string ToKebabCase(this global::Sample.Order.Line.Kind value)
        {
            switch (value)
            {
                case global::Sample.Order.Line.Kind.Product:
                    return "product";
                case global::Sample.Order.Line.Kind.Shipping:
                    return "shipping";
                default:
                    return ToKebabCaseFallback(value.ToOptimizedString());
            }
        }

        public static string ToLowerCase(this global::Sample.Order.Line.Kind value)
        {
            switch (value)
            {
                case global::Sample.Order.Line.Kind.Product:
                    return "Product".ToLowerInvariant();
                case global::Sample.Order.Line.Kind.Shipping:
                    return "Shipping".ToLowerInvariant();
                default:
                    return value.ToString().ToLowerInvariant();
            }
        }

        public static string ToUpperCase(this global::Sample.Order.Line.Kind value)
        {
            switch (value)
            {
                case global::Sample.Order.Line.Kind.Product:
                    return "Product".ToUpperInvariant();
                case global::Sample.Order.Line.Kind.Shipping:
                    return "Shipping".ToUpperInvariant();
                default:
                    return value.ToString().ToUpperInvariant();
            }
        }

        public static bool IsDefined(string name)
        {
            switch (name)
            {
                case "Product":
                case "Shipping":
                    return true;
                default:
                    return false;
            }
        }

        [global::System.Obsolete("Use TryParseWire/ParseWire")]
        public static bool TryParse(string? name, out global::Sample.Order.Line.Kind value)
        {
            switch (name)
            {
                case "Product":
                    value = global::Sample.Order.Line.Kind.Product;
                    return true;
                case "Shipping":
                    value = global::Sample.Order.Line.Kind.Shipping;
                    return true;
            }

            int numericValue;
            if (name != null && int.TryParse(name, out numericValue))
            {
                value = (global::Sample.Order.Line.Kind)numericValue;
                return true;
            }

            value = (global::Sample.Order.Line.Kind)0;
            return false;
        }

        [global::System.Obsolete("Use TryParseWire/ParseWire")]
        public static global::Sample.Order.Line.Kind Parse(string? name)
        {
            global::Sample.Order.Line.Kind value;
            if (TryParse(name, out value))
            {
                return value;
            }

            throw new global::System.ArgumentException("Requested value '" + name + "' was not found.");
        }

        public static string[] GetNames()
        {
            return new string[] { "Product", "Shipping" };
        }

        public static global::Sample.Order.Line.Kind[] GetValues()
        {
            return new global::Sample.Order.Line.Kind[] { global::Sample.Order.Line.Kind.Product, global::Sample.Order.Line.Kind.Shipping };
        }

        public static int AsUnderlyingType(this global::Sample.Order.Line.Kind value)
        {
            return (int)value;
        }

        private static string ToSnakeCaseFallback(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length + 4);
            global::System.Globalization.UnicodeCategory previous = global::System.Globalization.UnicodeCategory.OtherSymbol;
            bool isFirst = true;
            for (int i = 0; i < input.Length; i++)
            {
                char c = input[i];
                global::System.Globalization.UnicodeCategory current = char.GetUnicodeCategory(c);
                bool insertSeparator = CheckCategory(previous, current);
                bool isSpecial = IsSpecialCharacter(current);
                if (!isSpecial)
                {
                    if (insertSeparator && !isFirst) sb.Append('_');
                    sb.Append(char.ToLowerInvariant(c));
                    isFirst = false;
                }
                previous = current;
            }
            return sb.ToString();
        }

        private static string ToKebabCaseFallback(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length + 4);
            global::System.Globalization.UnicodeCategory previous = global::System.Globalization.UnicodeCategory.OtherSymbol;
            bool isFirst = true;
            for (int i = 0; i < input.Length; i++)
            {
                char c = input[i];
                global::System.Globalization.UnicodeCategory current = char.GetUnicodeCategory(c);
                bool insertSeparator = CheckCategory(previous, current);
                bool isSpecial = IsSpecialCharacter(current);
                if (!isSpecial)
                {
                    if (insertSeparator && !isFirst) sb.Append('-');
                    sb.Append(char.ToLowerInvariant(c));
                    isFirst = false;
                }
                previous = current;
            }
            return sb.ToString();
        }

        private static bool CheckCategory(global::System.Globalization.UnicodeCategory previous, global::System.Globalization.UnicodeCategory current)
        {
            return previous != current && (current == global::System.Globalization.UnicodeCategory.UppercaseLetter || current == global::System.Globalization.UnicodeCategory.DecimalDigitNumber || IsSpecialCharacter(previous) && !IsSpecialCharacter(current));
        }

        private static bool IsSpecialCharacter(global::System.Globalization.UnicodeCategory category)
        {
            return category != global::System.Globalization.UnicodeCategory.UppercaseLetter
                && category != global::System.Globalization.UnicodeCategory.LowercaseLetter
                && category != global::System.Globalization.UnicodeCategory.DecimalDigitNumber;
        }
    }
}
