//HintName: Sample.SignedExtensions.g.cs
// <auto-generated/>
#nullable enable

namespace Sample
{
    /// <summary>Generated helpers for <see cref="global::Sample.Signed"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("CSharpEssentials.Enums.Generators", "{version}")]
    public static class SignedExtensions
    {
        public const string NegativeSnakeCase = "negative";
        public const string NegativeKebabCase = "negative";
        public const string NegativeWireName = "negative";
        public const string MinSnakeCase = "min";
        public const string MinKebabCase = "min";
        public const string MinWireName = "min";
        public const string AliasSnakeCase = "alias";
        public const string AliasKebabCase = "alias";
        public const string AliasWireName = "alias";

        private static readonly global::CSharpEssentials.Enums.EnumConventions __WireReadConventions = global::CSharpEssentials.Enums.EnumConventions.Default with { UnknownValue = global::CSharpEssentials.Enums.UnknownEnumValueHandling.Reject };

        /// <summary>The canonical wire name. Throws <see cref="global::CSharpEssentials.Enums.EnumValueException"/> for undefined values.</summary>
        public static string ToWireName(this global::Sample.Signed value)
        {
            switch (value)
            {
                case global::Sample.Signed.Negative:
                    return NegativeWireName;
                case (global::Sample.Signed)(-9223372036854775807L - 1L):
                    return MinWireName;
                default:
                    return global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Signed>().Format(value, global::CSharpEssentials.Enums.EnumWireFormat.String);
            }
        }

        /// <summary>Parses with the data read rules (every known spelling, defined numbers), without the fallback member.</summary>
        public static bool TryParseWire(string? text, out global::Sample.Signed value)
        {
            if (text is null)
            {
                value = default;
                return false;
            }

            return global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Signed>().TryParse(text, global::CSharpEssentials.Enums.EnumReadMode.Data, __WireReadConventions, out value, out _);
        }

        /// <summary>Parses like <see cref="TryParseWire"/> and throws <see cref="global::CSharpEssentials.Enums.EnumValueException"/> on failure.</summary>
        public static global::Sample.Signed ParseWire(string? text)
        {
            global::CSharpEssentials.Enums.EnumInfo<global::Sample.Signed> info = global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Signed>();
            if (text is null)
                throw new global::CSharpEssentials.Enums.EnumValueException(info.CreateError(null, global::CSharpEssentials.Enums.EnumReadMode.Data));
            if (info.TryParse(text, global::CSharpEssentials.Enums.EnumReadMode.Data, __WireReadConventions, out global::Sample.Signed value, out global::CSharpEssentials.Enums.EnumValueError? error))
                return value;
            throw new global::CSharpEssentials.Enums.EnumValueException(error);
        }

        /// <summary>Whether <paramref name="value"/> is a defined member.</summary>
        public static bool IsDefined(this global::Sample.Signed value) => global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Signed>().IsDefined(value);

        internal static global::CSharpEssentials.Enums.EnumInfo<global::Sample.Signed> __CreateEnumInfo()
        {
            return new global::CSharpEssentials.Enums.EnumInfo<global::Sample.Signed>(
                new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Signed>[]
                {
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Signed>(global::Sample.Signed.Negative, 18446744073709551611UL, "Negative", NegativeWireName),
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Signed>((global::Sample.Signed)(-9223372036854775807L - 1L), 9223372036854775808UL, "Min", MinWireName) { IsObsolete = true },
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Signed>(global::Sample.Signed.Alias, 18446744073709551611UL, "Alias", AliasWireName),
                },
                static v => unchecked((ulong)(long)v),
                static r => unchecked((global::Sample.Signed)(long)r),
                false,
                (global::CSharpEssentials.Enums.EnumStorage)0);
        }

        public static string ToOptimizedString(this global::Sample.Signed value)
        {
            switch (value)
            {
                case global::Sample.Signed.Negative:
                    return "Negative";
                case (global::Sample.Signed)(-9223372036854775807L - 1L):
                    return "Min";
                default:
                    return value.ToString();
            }
        }

        [global::System.Obsolete("Use ToWireName()")]
        public static string ToSnakeCase(this global::Sample.Signed value)
        {
            switch (value)
            {
                case global::Sample.Signed.Negative:
                    return "negative";
                case (global::Sample.Signed)(-9223372036854775807L - 1L):
                    return "min";
                default:
                    return ToSnakeCaseFallback(value.ToOptimizedString());
            }
        }

        public static string ToKebabCase(this global::Sample.Signed value)
        {
            switch (value)
            {
                case global::Sample.Signed.Negative:
                    return "negative";
                case (global::Sample.Signed)(-9223372036854775807L - 1L):
                    return "min";
                default:
                    return ToKebabCaseFallback(value.ToOptimizedString());
            }
        }

        public static string ToLowerCase(this global::Sample.Signed value)
        {
            switch (value)
            {
                case global::Sample.Signed.Negative:
                    return "Negative".ToLowerInvariant();
                case (global::Sample.Signed)(-9223372036854775807L - 1L):
                    return "Min".ToLowerInvariant();
                default:
                    return value.ToString().ToLowerInvariant();
            }
        }

        public static string ToUpperCase(this global::Sample.Signed value)
        {
            switch (value)
            {
                case global::Sample.Signed.Negative:
                    return "Negative".ToUpperInvariant();
                case (global::Sample.Signed)(-9223372036854775807L - 1L):
                    return "Min".ToUpperInvariant();
                default:
                    return value.ToString().ToUpperInvariant();
            }
        }

        public static bool IsDefined(string name)
        {
            switch (name)
            {
                case "Negative":
                case "Min":
                case "Alias":
                    return true;
                default:
                    return false;
            }
        }

        [global::System.Obsolete("Use TryParseWire/ParseWire")]
        public static bool TryParse(string? name, out global::Sample.Signed value)
        {
            switch (name)
            {
                case "Negative":
                    value = global::Sample.Signed.Negative;
                    return true;
                case "Min":
                    value = (global::Sample.Signed)(-9223372036854775807L - 1L);
                    return true;
                case "Alias":
                    value = global::Sample.Signed.Alias;
                    return true;
            }

            long numericValue;
            if (name != null && long.TryParse(name, out numericValue))
            {
                value = (global::Sample.Signed)numericValue;
                return true;
            }

            value = (global::Sample.Signed)0;
            return false;
        }

        [global::System.Obsolete("Use TryParseWire/ParseWire")]
        public static global::Sample.Signed Parse(string? name)
        {
            global::Sample.Signed value;
            if (TryParse(name, out value))
            {
                return value;
            }

            throw new global::System.ArgumentException("Requested value '" + name + "' was not found.");
        }

        public static string[] GetNames()
        {
            return new string[] { "Negative", "Min", "Alias" };
        }

        public static global::Sample.Signed[] GetValues()
        {
            return new global::Sample.Signed[] { global::Sample.Signed.Negative, (global::Sample.Signed)(-9223372036854775807L - 1L), global::Sample.Signed.Alias };
        }

        public static long AsUnderlyingType(this global::Sample.Signed value)
        {
            return (long)value;
        }

        private static string ToSnakeCaseFallback(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length + 4);
            global::System.Globalization.UnicodeCategory previous = global::System.Globalization.UnicodeCategory.OtherSymbol;
            bool isFirst = true;
            for (int i = 0; i < input.Length; i++)
            {
                char c = input[i];
                global::System.Globalization.UnicodeCategory current = char.GetUnicodeCategory(c);
                bool insertSeparator = CheckCategory(previous, current);
                bool isSpecial = IsSpecialCharacter(current);
                if (!isSpecial)
                {
                    if (insertSeparator && !isFirst) sb.Append('_');
                    sb.Append(char.ToLowerInvariant(c));
                    isFirst = false;
                }
                previous = current;
            }
            return sb.ToString();
        }

        private static string ToKebabCaseFallback(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length + 4);
            global::System.Globalization.UnicodeCategory previous = global::System.Globalization.UnicodeCategory.OtherSymbol;
            bool isFirst = true;
            for (int i = 0; i < input.Length; i++)
            {
                char c = input[i];
                global::System.Globalization.UnicodeCategory current = char.GetUnicodeCategory(c);
                bool insertSeparator = CheckCategory(previous, current);
                bool isSpecial = IsSpecialCharacter(current);
                if (!isSpecial)
                {
                    if (insertSeparator && !isFirst) sb.Append('-');
                    sb.Append(char.ToLowerInvariant(c));
                    isFirst = false;
                }
                previous = current;
            }
            return sb.ToString();
        }

        private static bool CheckCategory(global::System.Globalization.UnicodeCategory previous, global::System.Globalization.UnicodeCategory current)
        {
            return previous != current && (current == global::System.Globalization.UnicodeCategory.UppercaseLetter || current == global::System.Globalization.UnicodeCategory.DecimalDigitNumber || IsSpecialCharacter(previous) && !IsSpecialCharacter(current));
        }

        private static bool IsSpecialCharacter(global::System.Globalization.UnicodeCategory category)
        {
            return category != global::System.Globalization.UnicodeCategory.UppercaseLetter
                && category != global::System.Globalization.UnicodeCategory.LowercaseLetter
                && category != global::System.Globalization.UnicodeCategory.DecimalDigitNumber;
        }
    }
}
