//HintName: Sample.ContractExtensions.g.cs
// <auto-generated/>
#nullable enable

namespace Sample
{
    /// <summary>Generated helpers for <see cref="global::Sample.Contract"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("CSharpEssentials.Enums.Generators", "{version}")]
    public static class ContractExtensions
    {
        public const string PendingApprovalSnakeCase = "pending_approval";
        public const string PendingApprovalKebabCase = "pending-approval";
        public const string PendingApprovalWireName = "pending-approval";
        public const string HTTPShippedSnakeCase = "httpshipped";
        public const string HTTPShippedKebabCase = "httpshipped";
        public const string HTTPShippedWireName = "shipped";
        public const string OnHoldSnakeCase = "on_hold";
        public const string OnHoldKebabCase = "on-hold";
        public const string OnHoldWireName = "on \"hold\"";
        public const string PausedSnakeCase = "paused";
        public const string PausedKebabCase = "paused";
        public const string PausedWireName = "paused";
        public const string UnknownSnakeCase = "unknown";
        public const string UnknownKebabCase = "unknown";
        public const string UnknownWireName = "unknown";

        private static readonly global::CSharpEssentials.Enums.EnumConventions __WireReadConventions = global::CSharpEssentials.Enums.EnumConventions.Default with { UnknownValue = global::CSharpEssentials.Enums.UnknownEnumValueHandling.Reject };

        /// <summary>The canonical wire name. Throws <see cref="global::CSharpEssentials.Enums.EnumValueException"/> for undefined values.</summary>
        public static string ToWireName(this global::Sample.Contract value)
        {
            switch (value)
            {
                case global::Sample.Contract.PendingApproval:
                    return PendingApprovalWireName;
                case global::Sample.Contract.HTTPShipped:
                    return HTTPShippedWireName;
                case global::Sample.Contract.OnHold:
                    return OnHoldWireName;
                case (global::Sample.Contract)3:
                    return PausedWireName;
                case global::Sample.Contract.Unknown:
                    return UnknownWireName;
                default:
                    return global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Contract>().Format(value, global::CSharpEssentials.Enums.EnumWireFormat.String);
            }
        }

        /// <summary>Parses with the data read rules (every known spelling, defined numbers), without the fallback member.</summary>
        public static bool TryParseWire(string? text, out global::Sample.Contract value)
        {
            if (text is null)
            {
                value = default;
                return false;
            }

            return global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Contract>().TryParse(text, global::CSharpEssentials.Enums.EnumReadMode.Data, __WireReadConventions, out value, out _);
        }

        /// <summary>Parses like <see cref="TryParseWire"/> and throws <see cref="global::CSharpEssentials.Enums.EnumValueException"/> on failure.</summary>
        public static global::Sample.Contract ParseWire(string? text)
        {
            global::CSharpEssentials.Enums.EnumInfo<global::Sample.Contract> info = global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Contract>();
            if (text is null)
                throw new global::CSharpEssentials.Enums.EnumValueException(info.CreateError(null, global::CSharpEssentials.Enums.EnumReadMode.Data));
            if (info.TryParse(text, global::CSharpEssentials.Enums.EnumReadMode.Data, __WireReadConventions, out global::Sample.Contract value, out global::CSharpEssentials.Enums.EnumValueError? error))
                return value;
            throw new global::CSharpEssentials.Enums.EnumValueException(error);
        }

        /// <summary>Whether <paramref name="value"/> is a defined member.</summary>
        public static bool IsDefined(this global::Sample.Contract value) => global::CSharpEssentials.Enums.EnumMetadata.Get<global::Sample.Contract>().IsDefined(value);

        internal static global::CSharpEssentials.Enums.EnumInfo<global::Sample.Contract> __CreateEnumInfo()
        {
            return new global::CSharpEssentials.Enums.EnumInfo<global::Sample.Contract>(
                new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Contract>[]
                {
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Contract>(global::Sample.Contract.PendingApproval, 0UL, "PendingApproval", PendingApprovalWireName) { Aliases = new string[] { "pending_approval" }, Description = "Waiting for approval." },
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Contract>(global::Sample.Contract.HTTPShipped, 1UL, "HTTPShipped", HTTPShippedWireName) { Aliases = new string[] { "Sent", "Dispatched", "httpshipped" }, Description = "Shipped to the customer" },
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Contract>(global::Sample.Contract.OnHold, 2UL, "OnHold", OnHoldWireName) { Aliases = new string[] { "on_hold" } },
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Contract>((global::Sample.Contract)3, 3UL, "Paused", PausedWireName) { IsObsolete = true },
                    new global::CSharpEssentials.Enums.EnumMemberInfo<global::Sample.Contract>(global::Sample.Contract.Unknown, 99UL, "Unknown", UnknownWireName) { IsFallback = true },
                },
                static v => unchecked((ulong)(long)v),
                static r => unchecked((global::Sample.Contract)(long)r),
                false,
                (global::CSharpEssentials.Enums.EnumStorage)2);
        }

        public static string ToOptimizedString(this global::Sample.Contract value)
        {
            switch (value)
            {
                case global::Sample.Contract.PendingApproval:
                    return "PendingApproval";
                case global::Sample.Contract.HTTPShipped:
                    return "HTTPShipped";
                case global::Sample.Contract.OnHold:
                    return "OnHold";
                case (global::Sample.Contract)3:
                    return "Paused";
                case global::Sample.Contract.Unknown:
                    return "Unknown";
                default:
                    return value.ToString();
            }
        }

        [global::System.Obsolete("Use ToWireName()")]
        public static string ToSnakeCase(this global::Sample.Contract value)
        {
            switch (value)
            {
                case global::Sample.Contract.PendingApproval:
                    return "pending_approval";
                case global::Sample.Contract.HTTPShipped:
                    return "httpshipped";
                case global::Sample.Contract.OnHold:
                    return "on_hold";
                case (global::Sample.Contract)3:
                    return "paused";
                case global::Sample.Contract.Unknown:
                    return "unknown";
                default:
                    return ToSnakeCaseFallback(value.ToOptimizedString());
            }
        }

        public static string ToKebabCase(this global::Sample.Contract value)
        {
            switch (value)
            {
                case global::Sample.Contract.PendingApproval:
                    return "pending-approval";
                case global::Sample.Contract.HTTPShipped:
                    return "httpshipped";
                case global::Sample.Contract.OnHold:
                    return "on-hold";
                case (global::Sample.Contract)3:
                    return "paused";
                case global::Sample.Contract.Unknown:
                    return "unknown";
                default:
                    return ToKebabCaseFallback(value.ToOptimizedString());
            }
        }

        public static string ToLowerCase(this global::Sample.Contract value)
        {
            switch (value)
            {
                case global::Sample.Contract.PendingApproval:
                    return "PendingApproval".ToLowerInvariant();
                case global::Sample.Contract.HTTPShipped:
                    return "HTTPShipped".ToLowerInvariant();
                case global::Sample.Contract.OnHold:
                    return "OnHold".ToLowerInvariant();
                case (global::Sample.Contract)3:
                    return "Paused".ToLowerInvariant();
                case global::Sample.Contract.Unknown:
                    return "Unknown".ToLowerInvariant();
                default:
                    return value.ToString().ToLowerInvariant();
            }
        }

        public static string ToUpperCase(this global::Sample.Contract value)
        {
            switch (value)
            {
                case global::Sample.Contract.PendingApproval:
                    return "PendingApproval".ToUpperInvariant();
                case global::Sample.Contract.HTTPShipped:
                    return "HTTPShipped".ToUpperInvariant();
                case global::Sample.Contract.OnHold:
                    return "OnHold".ToUpperInvariant();
                case (global::Sample.Contract)3:
                    return "Paused".ToUpperInvariant();
                case global::Sample.Contract.Unknown:
                    return "Unknown".ToUpperInvariant();
                default:
                    return value.ToString().ToUpperInvariant();
            }
        }

        public static bool IsDefined(string name)
        {
            switch (name)
            {
                case "PendingApproval":
                case "HTTPShipped":
                case "OnHold":
                case "Paused":
                case "Unknown":
                    return true;
                default:
                    return false;
            }
        }

        [global::System.Obsolete("Use TryParseWire/ParseWire")]
        public static bool TryParse(string? name, out global::Sample.Contract value)
        {
            switch (name)
            {
                case "PendingApproval":
                    value = global::Sample.Contract.PendingApproval;
                    return true;
                case "HTTPShipped":
                    value = global::Sample.Contract.HTTPShipped;
                    return true;
                case "OnHold":
                    value = global::Sample.Contract.OnHold;
                    return true;
                case "Paused":
                    value = (global::Sample.Contract)3;
                    return true;
                case "Unknown":
                    value = global::Sample.Contract.Unknown;
                    return true;
            }

            int numericValue;
            if (name != null && int.TryParse(name, out numericValue))
            {
                value = (global::Sample.Contract)numericValue;
                return true;
            }

            value = (global::Sample.Contract)0;
            return false;
        }

        [global::System.Obsolete("Use TryParseWire/ParseWire")]
        public static global::Sample.Contract Parse(string? name)
        {
            global::Sample.Contract value;
            if (TryParse(name, out value))
            {
                return value;
            }

            throw new global::System.ArgumentException("Requested value '" + name + "' was not found.");
        }

        public static string[] GetNames()
        {
            return new string[] { "PendingApproval", "HTTPShipped", "OnHold", "Paused", "Unknown" };
        }

        public static global::Sample.Contract[] GetValues()
        {
            return new global::Sample.Contract[] { global::Sample.Contract.PendingApproval, global::Sample.Contract.HTTPShipped, global::Sample.Contract.OnHold, (global::Sample.Contract)3, global::Sample.Contract.Unknown };
        }

        public static int AsUnderlyingType(this global::Sample.Contract value)
        {
            return (int)value;
        }

        private static string ToSnakeCaseFallback(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length + 4);
            global::System.Globalization.UnicodeCategory previous = global::System.Globalization.UnicodeCategory.OtherSymbol;
            bool isFirst = true;
            for (int i = 0; i < input.Length; i++)
            {
                char c = input[i];
                global::System.Globalization.UnicodeCategory current = char.GetUnicodeCategory(c);
                bool insertSeparator = CheckCategory(previous, current);
                bool isSpecial = IsSpecialCharacter(current);
                if (!isSpecial)
                {
                    if (insertSeparator && !isFirst) sb.Append('_');
                    sb.Append(char.ToLowerInvariant(c));
                    isFirst = false;
                }
                previous = current;
            }
            return sb.ToString();
        }

        private static string ToKebabCaseFallback(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder(input.Length + 4);
            global::System.Globalization.UnicodeCategory previous = global::System.Globalization.UnicodeCategory.OtherSymbol;
            bool isFirst = true;
            for (int i = 0; i < input.Length; i++)
            {
                char c = input[i];
                global::System.Globalization.UnicodeCategory current = char.GetUnicodeCategory(c);
                bool insertSeparator = CheckCategory(previous, current);
                bool isSpecial = IsSpecialCharacter(current);
                if (!isSpecial)
                {
                    if (insertSeparator && !isFirst) sb.Append('-');
                    sb.Append(char.ToLowerInvariant(c));
                    isFirst = false;
                }
                previous = current;
            }
            return sb.ToString();
        }

        private static bool CheckCategory(global::System.Globalization.UnicodeCategory previous, global::System.Globalization.UnicodeCategory current)
        {
            return previous != current && (current == global::System.Globalization.UnicodeCategory.UppercaseLetter || current == global::System.Globalization.UnicodeCategory.DecimalDigitNumber || IsSpecialCharacter(previous) && !IsSpecialCharacter(current));
        }

        private static bool IsSpecialCharacter(global::System.Globalization.UnicodeCategory category)
        {
            return category != global::System.Globalization.UnicodeCategory.UppercaseLetter
                && category != global::System.Globalization.UnicodeCategory.LowercaseLetter
                && category != global::System.Globalization.UnicodeCategory.DecimalDigitNumber;
        }
    }
}
