//HintName: SampleAppServiceAggregate.g.cs
// <auto-generated/>
#nullable enable
namespace Microsoft.Extensions.DependencyInjection
{
    [global::System.CodeDom.Compiler.GeneratedCode("CSharpEssentials.DependencyInjection.Generators", "{version}")]
    internal static class SampleAppServiceAggregate
    {
        internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddAllServices(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
            global::Microsoft.Extensions.Logging.ILogger? logger = null)
        {
            bool register0 = !global::CSharpEssentials.DependencyInjection.ServiceRegistration.IsRegistered(services, typeof(global::Microsoft.Extensions.DependencyInjection.SampleLibraryServiceRegistry).Assembly);
            bool register1 = !global::CSharpEssentials.DependencyInjection.ServiceRegistration.IsRegistered(services, typeof(global::Microsoft.Extensions.DependencyInjection.SampleAppServiceRegistry).Assembly);
            global::System.Collections.Generic.SortedSet<int> orders = new global::System.Collections.Generic.SortedSet<int>();

            if (register0)
            {
                global::Microsoft.Extensions.DependencyInjection.SampleLibraryServiceRegistry.RegisterServices(services, logger);
                orders.UnionWith(global::Microsoft.Extensions.DependencyInjection.SampleLibraryServiceRegistry.DecoratorOrders);
            }

            if (register1)
            {
                global::Microsoft.Extensions.DependencyInjection.SampleAppServiceRegistry.RegisterServices(services, logger);
                orders.UnionWith(global::Microsoft.Extensions.DependencyInjection.SampleAppServiceRegistry.DecoratorOrders);
            }

            foreach (int order in orders)
            {
                if (register0)
                {
                    global::Microsoft.Extensions.DependencyInjection.SampleLibraryServiceRegistry.ApplyDecorators(services, order);
                }

                if (register1)
                {
                    global::Microsoft.Extensions.DependencyInjection.SampleAppServiceRegistry.ApplyDecorators(services, order);
                }
            }

            if (register0)
            {
                global::CSharpEssentials.DependencyInjection.ServiceRegistration.MarkRegistered(services, typeof(global::Microsoft.Extensions.DependencyInjection.SampleLibraryServiceRegistry).Assembly);
            }

            if (register1)
            {
                global::CSharpEssentials.DependencyInjection.ServiceRegistration.MarkRegistered(services, typeof(global::Microsoft.Extensions.DependencyInjection.SampleAppServiceRegistry).Assembly);
            }

            return services;
        }
    }
}
