//HintName: GeneratorTestsServiceRegistry.g.cs
// <auto-generated/>
#nullable enable
[assembly: global::CSharpEssentials.DependencyInjection.ServiceModule(typeof(global::Microsoft.Extensions.DependencyInjection.GeneratorTestsServiceRegistry))]

namespace Microsoft.Extensions.DependencyInjection
{
    /// <summary>Registers the services and decorators declared in this assembly.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("CSharpEssentials.DependencyInjection.Generators", "4.0.0.0")]
    public static class GeneratorTestsServiceRegistry
    {
        /// <summary>Registers the services declared in this assembly, then applies its decorators. Calling it again, or after <c>AddAllServices</c>, does nothing.</summary>
        /// <param name="services">The service collection.</param>
        /// <param name="logger">An optional logger. Registrations whose service type and key already exist are logged at Debug.</param>
        /// <returns>The same service collection.</returns>
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratorTestsServices(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
            global::Microsoft.Extensions.Logging.ILogger? logger = null)
        {
            if (!global::CSharpEssentials.DependencyInjection.ServiceRegistration.TryMarkRegistered(services, typeof(GeneratorTestsServiceRegistry).Assembly))
            {
                return services;
            }

            RegisterServices(services, logger);
            ApplyDecorators(services);
            return services;
        }

        /// <summary>Registers the services declared in this assembly without applying decorators.</summary>
        /// <param name="services">The service collection.</param>
        /// <param name="logger">An optional logger for duplicate registrations.</param>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static void RegisterServices(
            global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
            global::Microsoft.Extensions.Logging.ILogger? logger)
        {
            global::CSharpEssentials.DependencyInjection.ServiceRegistration.Apply(
                services,
                logger,
                global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(typeof(global::Sample.IClock), typeof(global::Sample.Clock)),
                global::CSharpEssentials.DependencyInjection.RegistrationStrategy.Add);
            global::CSharpEssentials.DependencyInjection.ServiceRegistration.Apply(
                services,
                logger,
                new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Sample.IGreeter), global::Sample.Region.Eu, typeof(global::Sample.EuGreeter), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient),
                global::CSharpEssentials.DependencyInjection.RegistrationStrategy.Add);
            global::CSharpEssentials.DependencyInjection.ServiceRegistration.Apply(
                services,
                logger,
                global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped(typeof(global::Sample.Greeter), typeof(global::Sample.Greeter)),
                global::CSharpEssentials.DependencyInjection.RegistrationStrategy.TryAdd);
            global::CSharpEssentials.DependencyInjection.ServiceRegistration.Apply(
                services,
                logger,
                global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped<global::Sample.IAudit>(sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Sample.Greeter>(sp)),
                global::CSharpEssentials.DependencyInjection.RegistrationStrategy.TryAdd);
            global::CSharpEssentials.DependencyInjection.ServiceRegistration.Apply(
                services,
                logger,
                global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped<global::Sample.IGreeter>(sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Sample.Greeter>(sp)),
                global::CSharpEssentials.DependencyInjection.RegistrationStrategy.TryAdd);
            global::CSharpEssentials.DependencyInjection.ServiceRegistration.Apply(
                services,
                logger,
                new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Sample.IAudit), 42, typeof(global::Sample.NumberedClock), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton),
                global::CSharpEssentials.DependencyInjection.RegistrationStrategy.Add);
            global::CSharpEssentials.DependencyInjection.ServiceRegistration.Apply(
                services,
                logger,
                new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Sample.IClock), 42, typeof(global::Sample.NumberedClock), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton),
                global::CSharpEssentials.DependencyInjection.RegistrationStrategy.Add);
            global::CSharpEssentials.DependencyInjection.ServiceRegistration.Apply(
                services,
                logger,
                global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped(typeof(global::Sample.PlainClock), typeof(global::Sample.PlainClock)),
                global::CSharpEssentials.DependencyInjection.RegistrationStrategy.Add);
            global::CSharpEssentials.DependencyInjection.ServiceRegistration.Apply(
                services,
                logger,
                global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped(typeof(global::Sample.IRepository<>), typeof(global::Sample.Repository<>)),
                global::CSharpEssentials.DependencyInjection.RegistrationStrategy.Add);
            global::CSharpEssentials.DependencyInjection.ServiceRegistration.Apply(
                services,
                logger,
                new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Sample.SharedGreeter), "shared", typeof(global::Sample.SharedGreeter), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton),
                global::CSharpEssentials.DependencyInjection.RegistrationStrategy.Add);
            global::CSharpEssentials.DependencyInjection.ServiceRegistration.Apply(
                services,
                logger,
                global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.KeyedSingleton<global::Sample.IAudit>("shared", (sp, _) => global::Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService<global::Sample.SharedGreeter>(sp, "shared")),
                global::CSharpEssentials.DependencyInjection.RegistrationStrategy.Add);
            global::CSharpEssentials.DependencyInjection.ServiceRegistration.Apply(
                services,
                logger,
                global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.KeyedSingleton<global::Sample.IGreeter>("shared", (sp, _) => global::Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService<global::Sample.SharedGreeter>(sp, "shared")),
                global::CSharpEssentials.DependencyInjection.RegistrationStrategy.Add);
            global::CSharpEssentials.DependencyInjection.ServiceRegistration.Apply(
                services,
                logger,
                new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::Sample.IClock), typeof(int), typeof(global::Sample.TypedClock), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient),
                global::CSharpEssentials.DependencyInjection.RegistrationStrategy.Add);
        }

        /// <summary>Gets the distinct decorator orders declared in this assembly, ascending.</summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static global::System.Collections.Generic.IReadOnlyList<int> DecoratorOrders { get; } = new int[] { 1, 2 };

        /// <summary>Applies the decorators declared in this assembly.</summary>
        /// <param name="services">The service collection.</param>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static void ApplyDecorators(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            foreach (int order in DecoratorOrders)
            {
                ApplyDecorators(services, order);
            }
        }

        /// <summary>Applies the decorators declared in this assembly with the given order.</summary>
        /// <param name="services">The service collection.</param>
        /// <param name="order">The decorator order to apply.</param>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static void ApplyDecorators(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, int order)
        {
            switch (order)
            {
                case 1:
                    global::Microsoft.Extensions.DependencyInjection.ServiceCollectionDecorationExtensions.Decorate<global::Sample.IGreeter>(
                        services,
                        (inner, sp) => new global::Sample.EuDecorator(
                            inner,
                            (global::Sample.Region)(object)global::Sample.Region.Eu),
                        serviceKey: global::Sample.Region.Eu);
                    break;
                case 2:
                    global::Microsoft.Extensions.DependencyInjection.ServiceCollectionDecorationExtensions.Decorate<global::Sample.IGreeter>(
                        services,
                        (inner, sp) => new global::Sample.LoudGreeter(
                            inner,
                            global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Sample.IClock>(sp),
                            global::Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService<global::Sample.IAudit>(sp, "shared"),
                            (int)(sp.GetService(typeof(int)) ?? (object?)3)!),
                        serviceKey: null);
                    break;
            }
        }
    }
}
