//HintName: SampleAppServiceAggregate.g.cs
// <auto-generated/>
#nullable enable
namespace Microsoft.Extensions.DependencyInjection
{
    [global::System.CodeDom.Compiler.GeneratedCode("CSharpEssentials.DependencyInjection.Generators", "4.0.0.0")]
    internal static class SampleAppServiceAggregate
    {
        internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddAllServices(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
            global::Microsoft.Extensions.Logging.ILogger? logger = null)
        {
            global::Microsoft.Extensions.DependencyInjection.SampleLibraryServiceRegistry.RegisterServices(services, logger);
            global::Microsoft.Extensions.DependencyInjection.SampleAppServiceRegistry.RegisterServices(services, logger);
            global::Microsoft.Extensions.DependencyInjection.SampleLibraryServiceRegistry.ApplyDecorators(services);
            global::Microsoft.Extensions.DependencyInjection.SampleAppServiceRegistry.ApplyDecorators(services);
            return services;
        }
    }
}
