//HintName: SampleApiEndpointRegistry.g.cs
// <auto-generated/>
#nullable enable
[assembly: global::CSharpEssentials.Endpoints.EndpointModule(typeof(global::Microsoft.AspNetCore.Builder.SampleApiEndpointRegistry))]

namespace Microsoft.AspNetCore.Builder
{
    /// <summary>Maps the endpoints declared in this assembly.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("CSharpEssentials.Endpoints.Generators", "{version}")]
    public static class SampleApiEndpointRegistry
    {
        /// <summary>Gets the mapped endpoint types in mapping order.</summary>
        public static global::System.Collections.Generic.IReadOnlyList<global::System.Type> EndpointTypes { get; } = new global::System.Type[]
        {
            typeof(global::Sample.Api.Health),
            typeof(global::Sample.Api.Nested.Status),
            typeof(global::Sample.Api.CreateApp),
            typeof(global::Sample.Api.DeleteApp),
            typeof(global::Sample.Api.ListVersions),
        };

        /// <summary>Maps the endpoints declared in this assembly.</summary>
        /// <param name="app">The route builder.</param>
        /// <param name="configure">Optional mapping options.</param>
        /// <returns>The same route builder.</returns>
        public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapSampleApiEndpoints(
            this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app,
            global::System.Action<global::CSharpEssentials.Endpoints.EndpointMappingOptions>? configure = null)
        {
            MapEndpoints(app, global::CSharpEssentials.Endpoints.EndpointMapper.CreateOptions(configure));
            return app;
        }

        /// <summary>Maps the endpoints declared in this assembly with existing options.</summary>
        /// <param name="app">The route builder.</param>
        /// <param name="options">The mapping options.</param>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static void MapEndpoints(
            global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app,
            global::CSharpEssentials.Endpoints.EndpointMappingOptions options)
        {
            global::CSharpEssentials.Endpoints.EndpointMapper.MapEndpoint<global::Sample.Api.Health>(app, null, options);
            global::CSharpEssentials.Endpoints.EndpointMapper.MapEndpoint<global::Sample.Api.Nested.Status>(app, null, options);
            if (global::CSharpEssentials.Endpoints.EndpointMapper.ShouldMapAny(app, options, typeof(global::Sample.Api.CreateApp), typeof(global::Sample.Api.DeleteApp), typeof(global::Sample.Api.ListVersions)))
            {
                var appsGroup = global::CSharpEssentials.Endpoints.EndpointMapper.MapGroup<global::Sample.Api.AppsGroup>(app);
                global::CSharpEssentials.Endpoints.EndpointMapper.MapEndpoint<global::Sample.Api.CreateApp>(appsGroup, typeof(global::Sample.Api.AppsGroup), options);
                global::CSharpEssentials.Endpoints.EndpointMapper.MapEndpoint<global::Sample.Api.DeleteApp>(appsGroup, typeof(global::Sample.Api.AppsGroup), options);
                if (global::CSharpEssentials.Endpoints.EndpointMapper.ShouldMapAny(appsGroup, options, typeof(global::Sample.Api.ListVersions)))
                {
                    var appVersionsGroup = global::CSharpEssentials.Endpoints.EndpointMapper.MapGroup<global::Sample.Api.AppVersionsGroup>(appsGroup);
                    global::CSharpEssentials.Endpoints.EndpointMapper.MapEndpoint<global::Sample.Api.ListVersions>(appVersionsGroup, typeof(global::Sample.Api.AppVersionsGroup), options);
                }
            }
        }
    }
}
