//HintName: SampleNamedEndpointRegistry.g.cs
// <auto-generated/>
#nullable enable
[assembly: global::CSharpEssentials.Endpoints.EndpointModule(typeof(global::Microsoft.AspNetCore.Builder.SampleNamedEndpointRegistry))]

namespace Microsoft.AspNetCore.Builder
{
    /// <summary>Maps the endpoints declared in this assembly.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("CSharpEssentials.Endpoints.Generators", "{version}")]
    public static class SampleNamedEndpointRegistry
    {
        /// <summary>Gets the mapped endpoint types in mapping order.</summary>
        public static global::System.Collections.Generic.IReadOnlyList<global::System.Type> EndpointTypes { get; } = new global::System.Type[]
        {
            typeof(global::Sample.Named.Items),
        };

        private static readonly string[] ReservedEndpointNames = new string[]
        {
            "ArchiveItems",
            "Items",
            "Legacy\"Quoted",
            "LegacyMetadata",
            "LegacyRoute",
        };

        /// <summary>Maps the endpoints declared in this assembly.</summary>
        /// <param name="app">The route builder.</param>
        /// <param name="configure">Optional mapping options.</param>
        /// <returns>The same route builder.</returns>
        public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapSampleNamedEndpoints(
            this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app,
            global::System.Action<global::CSharpEssentials.Endpoints.EndpointMappingOptions>? configure = null)
        {
            MapEndpoints(app, global::CSharpEssentials.Endpoints.EndpointMapper.CreateOptions(configure));
            return app;
        }

        /// <summary>Maps the endpoints declared in this assembly with existing options.</summary>
        /// <param name="app">The route builder.</param>
        /// <param name="options">The mapping options.</param>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static void MapEndpoints(
            global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app,
            global::CSharpEssentials.Endpoints.EndpointMappingOptions options)
        {
            global::CSharpEssentials.Endpoints.EndpointMapper.ReserveEndpointNames(app, options, ReservedEndpointNames);
            global::CSharpEssentials.Endpoints.EndpointMapper.MapEndpoint<global::Sample.Named.Items>(app, null, options);
        }
    }
}
