//HintName: SampleHostEndpointAggregate.g.cs
// <auto-generated/>
#nullable enable
namespace Microsoft.AspNetCore.Builder
{
    [global::System.CodeDom.Compiler.GeneratedCode("CSharpEssentials.Endpoints.Generators", "{version}")]
    internal static class SampleHostEndpointAggregate
    {
        internal static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapAllEndpoints(
            this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app,
            global::System.Action<global::CSharpEssentials.Endpoints.EndpointMappingOptions>? configure = null)
        {
            var options = global::CSharpEssentials.Endpoints.EndpointMapper.CreateOptions(configure);
            global::Microsoft.AspNetCore.Builder.SampleHostEndpointRegistry.MapEndpoints(app, options);
            global::Microsoft.AspNetCore.Builder.SampleApiEndpointRegistry.MapEndpoints(app, options);
            global::Microsoft.AspNetCore.Builder.SampleModulesBillingEndpointRegistry.MapEndpoints(app, options);
            return app;
        }
    }
}
