using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace CSharpEssentials.Endpoints.Generators;

internal static class EndpointSourceWriter
{
    private const string Mapper = "global::CSharpEssentials.Endpoints.EndpointMapper";

    private const string RouteBuilder = "global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder";

    private const string Options = "global::CSharpEssentials.Endpoints.EndpointMappingOptions";

    private const string Configure = "global::System.Action<global::CSharpEssentials.Endpoints.EndpointMappingOptions>? configure = null";

    private static readonly string GeneratedCode =
        $"[global::System.CodeDom.Compiler.GeneratedCode(\"CSharpEssentials.Endpoints.Generators\", \"{typeof(EndpointSourceWriter).Assembly.GetName().Version}\")]";

    public static string WriteRegistry(string registryName, EquatableArray<EndpointModel> endpoints)
    {
        var root = GroupNode.Build(endpoints);
        string className = registryName + "EndpointRegistry";
        StringBuilder sb = new();
        sb.Append("// <auto-generated/>\n");
        sb.Append("#nullable enable\n");
        sb.Append("[assembly: global::CSharpEssentials.Endpoints.EndpointModule(typeof(global::Microsoft.AspNetCore.Builder.").Append(className).Append("))]\n");
        sb.Append('\n');
        sb.Append("namespace Microsoft.AspNetCore.Builder\n");
        sb.Append("{\n");
        sb.Append("    /// <summary>Maps the endpoints declared in this assembly.</summary>\n");
        sb.Append("    ").Append(GeneratedCode).Append('\n');
        sb.Append("    public static class ").Append(className).Append('\n');
        sb.Append("    {\n");
        sb.Append("        /// <summary>Gets the mapped endpoint types in mapping order.</summary>\n");
        sb.Append("        public static global::System.Collections.Generic.IReadOnlyList<global::System.Type> EndpointTypes { get; } = new global::System.Type[]\n");
        sb.Append("        {\n");
        foreach (EndpointModel endpoint in root.InMappingOrder())
        {
            sb.Append("            typeof(").Append(endpoint.FullyQualifiedName).Append("),\n");
        }

        sb.Append("        };\n");
        sb.Append('\n');
        sb.Append("        /// <summary>Maps the endpoints declared in this assembly.</summary>\n");
        sb.Append("        /// <param name=\"app\">The route builder.</param>\n");
        sb.Append("        /// <param name=\"configure\">Optional mapping options.</param>\n");
        sb.Append("        /// <returns>The same route builder.</returns>\n");
        sb.Append("        public static ").Append(RouteBuilder).Append(" Map").Append(registryName).Append("Endpoints(\n");
        sb.Append("            this ").Append(RouteBuilder).Append(" app,\n");
        sb.Append("            ").Append(Configure).Append(")\n");
        sb.Append("        {\n");
        sb.Append("            MapEndpoints(app, ").Append(Mapper).Append(".CreateOptions(configure));\n");
        sb.Append("            return app;\n");
        sb.Append("        }\n");
        sb.Append('\n');
        sb.Append("        /// <summary>Maps the endpoints declared in this assembly with existing options.</summary>\n");
        sb.Append("        /// <param name=\"app\">The route builder.</param>\n");
        sb.Append("        /// <param name=\"options\">The mapping options.</param>\n");
        sb.Append("        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]\n");
        sb.Append("        public static void MapEndpoints(\n");
        sb.Append("            ").Append(RouteBuilder).Append(" app,\n");
        sb.Append("            ").Append(Options).Append(" options)\n");
        sb.Append("        {\n");
        HashSet<string> variables = [with(StringComparer.Ordinal), "app", "options", "configure"];
        WriteNode(sb, root, "app", "null", 3, variables);
        sb.Append("        }\n");
        sb.Append("    }\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    public static string WriteAggregate(HostModel host, bool includeOwnRegistry)
    {
        StringBuilder sb = new();
        sb.Append("// <auto-generated/>\n");
        sb.Append("#nullable enable\n");
        sb.Append("namespace Microsoft.AspNetCore.Builder\n");
        sb.Append("{\n");
        sb.Append("    ").Append(GeneratedCode).Append('\n');
        sb.Append("    internal static class ").Append(host.RegistryName).Append("EndpointAggregate\n");
        sb.Append("    {\n");
        sb.Append("        internal static ").Append(RouteBuilder).Append(" MapAllEndpoints(\n");
        sb.Append("            this ").Append(RouteBuilder).Append(" app,\n");
        sb.Append("            ").Append(Configure).Append(")\n");
        sb.Append("        {\n");
        sb.Append("            var options = ").Append(Mapper).Append(".CreateOptions(configure);\n");
        string ownRegistry = "global::Microsoft.AspNetCore.Builder." + host.RegistryName + "EndpointRegistry";
        if (includeOwnRegistry)
        {
            sb.Append("            ").Append(ownRegistry).Append(".MapEndpoints(app, options);\n");
        }

        foreach (ReferencedRegistry registry in host.ReferencedRegistries)
        {
            if (includeOwnRegistry && string.Equals(registry.FullyQualifiedName, ownRegistry, StringComparison.Ordinal))
            {
                continue;
            }

            sb.Append("            ").Append(registry.FullyQualifiedName).Append(".MapEndpoints(app, options);\n");
        }

        sb.Append("            return app;\n");
        sb.Append("        }\n");
        sb.Append("    }\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    private static void WriteNode(StringBuilder sb, GroupNode node, string parent, string innermostGroup, int depth, HashSet<string> variables)
    {
        string indent = new(' ', depth * 4);
        foreach (EndpointModel endpoint in node.Endpoints)
        {
            sb.Append(indent).Append(Mapper).Append(".MapEndpoint<").Append(endpoint.FullyQualifiedName).Append(">(")
                .Append(parent).Append(", ").Append(innermostGroup).Append(", options);\n");
        }

        foreach (GroupNode child in node.Children.Values)
        {
            GroupModel group = child.Group!;
            string variable = CreateVariableName(group.Name, variables);
            sb.Append(indent).Append("if (").Append(Mapper).Append(".ShouldMapAny(").Append(parent).Append(", options");
            foreach (EndpointModel endpoint in child.InMappingOrder())
            {
                sb.Append(", typeof(").Append(endpoint.FullyQualifiedName).Append(')');
            }

            sb.Append("))\n");
            sb.Append(indent).Append("{\n");
            sb.Append(indent).Append("    var ").Append(variable).Append(" = ").Append(Mapper).Append(".MapGroup<")
                .Append(group.FullyQualifiedName).Append(">(").Append(parent).Append(");\n");
            WriteNode(sb, child, variable, $"typeof({group.FullyQualifiedName})", depth + 1, variables);
            sb.Append(indent).Append("}\n");
        }
    }

    private static string CreateVariableName(string typeName, HashSet<string> variables)
    {
        string baseName = char.ToLowerInvariant(typeName[0]) + typeName.Substring(1);
        string name = baseName;
        int suffix = 1;
        while (!variables.Add(name) || SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None)
        {
            suffix++;
            name = baseName + suffix.ToString(CultureInfo.InvariantCulture);
        }

        return name;
    }
}
