using System.Collections.Immutable;
using FluentAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace CSharpEssentials.Tests.EntityFrameworkCore.QueryFilters;

public sealed class IgnoreQueryFiltersAnalyzerTests
{
    private const string Prelude = """
        using System.Linq;
        using CSharpEssentials.Entity.Interfaces;
        using Microsoft.EntityFrameworkCore;

        namespace Sample;

        public sealed class Document : ISoftDeletableBase
        {
            public bool IsDeleted { get; set; }
        }

        public static class Queries
        {
            public static IQueryable<Document> Run(IQueryable<Document> query) =>
        """;

    private const string Epilogue = """
        ;
        }
        """;

    [Theory]
    [InlineData("query.IgnoreQueryFilters()")]
    [InlineData("query.Where(document => document.IsDeleted).IgnoreQueryFilters()")]
    [InlineData("EntityFrameworkQueryableExtensions.IgnoreQueryFilters(query)")]
    [InlineData("query.IgnoreQueryFilters<Document>()")]
    [InlineData("query?.IgnoreQueryFilters()")]
    public async Task Analyzer_Should_Report_CSE3001_When_Parameterless_Overload_Is_Called_And_Named_Overload_Exists(string expression)
    {
        Compilation compilation = Create(expression, QueryFilterAnalysis.EfCore10Reference);

        ImmutableArray<Diagnostic> diagnostics = await QueryFilterAnalysis.GetDiagnosticsAsync(compilation);

        Diagnostic diagnostic = diagnostics.Should().ContainSingle().Subject;
        diagnostic.Severity.Should().Be(DiagnosticSeverity.Info);
        diagnostic.GetMessage(System.Globalization.CultureInfo.InvariantCulture).Should().Contain("'Document'");
    }

    [Fact]
    public async Task Analyzer_Should_Report_On_The_Method_Name_When_Called_As_Extension()
    {
        Compilation compilation = Create("query.IgnoreQueryFilters()", QueryFilterAnalysis.EfCore10Reference);

        Diagnostic diagnostic = (await QueryFilterAnalysis.GetDiagnosticsAsync(compilation)).Should().ContainSingle().Subject;

        (await diagnostic.Location.SourceTree!.GetTextAsync()).ToString(diagnostic.Location.SourceSpan).Should().Be("IgnoreQueryFilters");
    }

    [Fact]
    public async Task Analyzer_Should_Report_On_The_Method_Name_When_Called_With_Conditional_Access()
    {
        Compilation compilation = Create("query?.IgnoreQueryFilters()", QueryFilterAnalysis.EfCore10Reference);

        Diagnostic diagnostic = (await QueryFilterAnalysis.GetDiagnosticsAsync(compilation)).Should().ContainSingle().Subject;

        (await diagnostic.Location.SourceTree!.GetTextAsync()).ToString(diagnostic.Location.SourceSpan).Should().Be("IgnoreQueryFilters");
    }

    [Fact]
    public async Task Analyzer_Should_Report_CSE3001_When_Extension_Is_Imported_With_Using_Static()
    {
        string source = (Prelude + "query.IgnoreQueryFilters()" + Epilogue).Replace(
            "using Microsoft.EntityFrameworkCore;",
            "using static Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions;",
            StringComparison.Ordinal);
        Compilation compilation = QueryFilterAnalysis.CreateCompilation(source, LanguageVersion.Latest, QueryFilterAnalysis.EfCore10Reference);

        ImmutableArray<Diagnostic> diagnostics = await QueryFilterAnalysis.GetDiagnosticsAsync(compilation);

        diagnostics.Should().ContainSingle();
    }

    [Fact]
    public async Task Analyzer_Should_Report_CSE3001_When_Entity_Is_A_Generic_Type_Parameter()
    {
        string source = (Prelude + "query.IgnoreQueryFilters()" + Epilogue).Replace(
            "public static IQueryable<Document> Run(IQueryable<Document> query) =>",
            "public static IQueryable<T> Run<T>(IQueryable<T> query) where T : class, ISoftDeletableBase =>",
            StringComparison.Ordinal);
        Compilation compilation = QueryFilterAnalysis.CreateCompilation(source, LanguageVersion.Latest, QueryFilterAnalysis.EfCore10Reference);

        Diagnostic diagnostic = (await QueryFilterAnalysis.GetDiagnosticsAsync(compilation)).Should().ContainSingle().Subject;

        diagnostic.GetMessage(System.Globalization.CultureInfo.InvariantCulture).Should().Contain("'T'");
    }

    [Fact]
    public async Task Analyzer_Should_Not_Report_In_Generated_Code()
    {
        string source = "// <auto-generated/>\n" + Prelude + "query.IgnoreQueryFilters()" + Epilogue;
        Compilation compilation = QueryFilterAnalysis.CreateCompilation(source, LanguageVersion.Latest, QueryFilterAnalysis.EfCore10Reference);

        ImmutableArray<Diagnostic> diagnostics = await QueryFilterAnalysis.GetDiagnosticsAsync(compilation);

        diagnostics.Should().BeEmpty();
    }

    [Theory]
    [InlineData("query.IgnoreQueryFilters([\"SoftDelete\"])")]
    [InlineData("query.IgnoreQueryFilters(new[] { \"SoftDelete\", \"Tenant\" })")]
    [InlineData("EntityFrameworkQueryableExtensions.IgnoreQueryFilters(query, [\"SoftDelete\"])")]
    public async Task Analyzer_Should_Not_Report_When_Named_Overload_Is_Called(string expression)
    {
        Compilation compilation = Create(expression, QueryFilterAnalysis.EfCore10Reference);

        (await QueryFilterAnalysis.GetDiagnosticsAsync(compilation)).Should().BeEmpty();
    }

    [Fact]
    public async Task Analyzer_Should_Not_Report_When_IgnoreQueryFilters_Is_Not_The_EF_Core_Method()
    {
        const string source = """
            using System.Linq;

            namespace Sample.Filters
            {
                public static class QueryableFilterExtensions
                {
                    public static IQueryable<T> IgnoreQueryFilters<T>(this IQueryable<T> source) => source;
                }
            }

            namespace Sample
            {
                using Sample.Filters;

                public static class Queries
                {
                    public static IQueryable<string> Run(IQueryable<string> query) => query.IgnoreQueryFilters();
                }
            }
            """;
        Compilation compilation = QueryFilterAnalysis.CreateCompilation(source, LanguageVersion.Latest, QueryFilterAnalysis.EfCore10Reference);

        (await QueryFilterAnalysis.GetDiagnosticsAsync(compilation)).Should().BeEmpty();
    }

    [Fact]
    public async Task Analyzer_Should_Not_Report_When_Named_Overload_Does_Not_Exist()
    {
        Compilation compilation = Create("query.IgnoreQueryFilters()", QueryFilterAnalysis.EfCore9Reference);

        (await QueryFilterAnalysis.GetDiagnosticsAsync(compilation)).Should().BeEmpty();
    }

    [Fact]
    public async Task Analyzer_Should_Compile_The_Sample_Against_EF_Core_9()
    {
        Compilation compilation = Create("query.IgnoreQueryFilters()", QueryFilterAnalysis.EfCore9Reference);

        compilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error).Should().BeEmpty();
    }

    private static CSharpCompilation Create(string expression, MetadataReference efCore) =>
        QueryFilterAnalysis.CreateCompilation(Prelude + expression + Epilogue, LanguageVersion.Latest, efCore);
}
