using System.Globalization;
using System.Text;

namespace CSharpEssentials.DependencyInjection.Generators;

internal static class ServiceSourceWriter
{
    private const string Services = "global::Microsoft.Extensions.DependencyInjection.IServiceCollection";

    private const string Logger = "global::Microsoft.Extensions.Logging.ILogger";

    private const string Descriptor = "global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor";

    private const string Lifetime = "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime";

    private const string Resolve = "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions";

    private const string ResolveKeyed = "global::Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions";

    private const string Registration = "global::CSharpEssentials.DependencyInjection.ServiceRegistration";

    private const string Decoration = "global::Microsoft.Extensions.DependencyInjection.ServiceCollectionDecorationExtensions";

    private const string NeverBrowsable =
        "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]";

    private static readonly string GeneratedCode =
        $"[global::System.CodeDom.Compiler.GeneratedCode(\"CSharpEssentials.DependencyInjection.Generators\", \"{typeof(ServiceSourceWriter).Assembly.GetName().Version}\")]";

    public static string WriteRegistry(string registryName, EquatableArray<ServiceTypeModel> types)
    {
        string className = registryName + "ServiceRegistry";
        StringBuilder sb = new();
        sb.Append("// <auto-generated/>\n");
        sb.Append("#nullable enable\n");
        sb.Append("[assembly: global::CSharpEssentials.DependencyInjection.ServiceModule(typeof(global::Microsoft.Extensions.DependencyInjection.")
            .Append(className).Append("))]\n");
        sb.Append('\n');
        sb.Append("namespace Microsoft.Extensions.DependencyInjection\n");
        sb.Append("{\n");
        sb.Append("    /// <summary>Registers the services and decorators declared in this assembly.</summary>\n");
        sb.Append("    ").Append(GeneratedCode).Append('\n');
        sb.Append("    public static class ").Append(className).Append('\n');
        sb.Append("    {\n");
        sb.Append("        /// <summary>Registers the services declared in this assembly, then applies its decorators.</summary>\n");
        sb.Append("        /// <param name=\"services\">The service collection.</param>\n");
        sb.Append("        /// <param name=\"logger\">An optional logger. Registrations whose service type and key already exist are logged at Debug.</param>\n");
        sb.Append("        /// <returns>The same service collection.</returns>\n");
        sb.Append("        public static ").Append(Services).Append(" Add").Append(registryName).Append("Services(\n");
        sb.Append("            this ").Append(Services).Append(" services,\n");
        sb.Append("            ").Append(Logger).Append("? logger = null)\n");
        sb.Append("        {\n");
        sb.Append("            RegisterServices(services, logger);\n");
        sb.Append("            ApplyDecorators(services);\n");
        sb.Append("            return services;\n");
        sb.Append("        }\n");
        sb.Append('\n');
        sb.Append("        /// <summary>Registers the services declared in this assembly without applying decorators.</summary>\n");
        sb.Append("        /// <param name=\"services\">The service collection.</param>\n");
        sb.Append("        /// <param name=\"logger\">An optional logger for duplicate registrations.</param>\n");
        sb.Append("        ").Append(NeverBrowsable).Append('\n');
        sb.Append("        public static void RegisterServices(\n");
        sb.Append("            ").Append(Services).Append(" services,\n");
        sb.Append("            ").Append(Logger).Append("? logger)\n");
        sb.Append("        {\n");
        foreach (ServiceTypeModel type in types)
        {
            foreach (RegistrationModel registration in type.Registrations)
            {
                WriteRegistration(sb, registration);
            }
        }

        sb.Append("        }\n");
        sb.Append('\n');
        DecoratorModel[] decorators = [.. types
            .SelectMany(static type => type.Decorators)
            .OrderBy(static decorator => decorator.Order)
            .ThenBy(static decorator => decorator.SortName, StringComparer.Ordinal)];
        int[] orders = [.. decorators.Select(static decorator => decorator.Order).Distinct()];

        sb.Append("        /// <summary>Gets the distinct decorator orders declared in this assembly, ascending.</summary>\n");
        sb.Append("        ").Append(NeverBrowsable).Append('\n');
        sb.Append("        public static global::System.Collections.Generic.IReadOnlyList<int> DecoratorOrders { get; } = ");
        if (orders.Length == 0)
        {
            sb.Append("global::System.Array.Empty<int>();\n");
        }
        else
        {
            sb.Append("new int[] { ").Append(string.Join(", ", orders.Select(static order => order.ToString(CultureInfo.InvariantCulture)))).Append(" };\n");
        }

        sb.Append('\n');
        sb.Append("        /// <summary>Applies the decorators declared in this assembly.</summary>\n");
        sb.Append("        /// <param name=\"services\">The service collection.</param>\n");
        sb.Append("        ").Append(NeverBrowsable).Append('\n');
        sb.Append("        public static void ApplyDecorators(").Append(Services).Append(" services)\n");
        sb.Append("        {\n");
        sb.Append("            foreach (int order in DecoratorOrders)\n");
        sb.Append("            {\n");
        sb.Append("                ApplyDecorators(services, order);\n");
        sb.Append("            }\n");
        sb.Append("        }\n");
        sb.Append('\n');
        sb.Append("        /// <summary>Applies the decorators declared in this assembly with the given order.</summary>\n");
        sb.Append("        /// <param name=\"services\">The service collection.</param>\n");
        sb.Append("        /// <param name=\"order\">The decorator order to apply.</param>\n");
        sb.Append("        ").Append(NeverBrowsable).Append('\n');
        sb.Append("        public static void ApplyDecorators(").Append(Services).Append(" services, int order)\n");
        sb.Append("        {\n");
        if (orders.Length > 0)
        {
            sb.Append("            switch (order)\n");
            sb.Append("            {\n");
            foreach (int order in orders)
            {
                sb.Append("                case ").Append(order.ToString(CultureInfo.InvariantCulture)).Append(":\n");
                foreach (DecoratorModel decorator in decorators.Where(decorator => decorator.Order == order))
                {
                    WriteDecorator(sb, decorator);
                }

                sb.Append("                    break;\n");
            }

            sb.Append("            }\n");
        }

        sb.Append("        }\n");
        sb.Append("    }\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    public static string WriteAggregate(HostModel host, bool includeOwnRegistry)
    {
        List<string> registries = [.. host.ReferencedRegistries.Select(static registry => registry.FullyQualifiedName)];
        if (includeOwnRegistry)
        {
            registries.Add("global::Microsoft.Extensions.DependencyInjection." + host.RegistryName + "ServiceRegistry");
        }

        StringBuilder sb = new();
        sb.Append("// <auto-generated/>\n");
        sb.Append("#nullable enable\n");
        sb.Append("namespace Microsoft.Extensions.DependencyInjection\n");
        sb.Append("{\n");
        sb.Append("    ").Append(GeneratedCode).Append('\n');
        sb.Append("    internal static class ").Append(host.RegistryName).Append("ServiceAggregate\n");
        sb.Append("    {\n");
        sb.Append("        internal static ").Append(Services).Append(" AddAllServices(\n");
        sb.Append("            this ").Append(Services).Append(" services,\n");
        sb.Append("            ").Append(Logger).Append("? logger = null)\n");
        sb.Append("        {\n");
        foreach (string registry in registries)
        {
            sb.Append("            ").Append(registry).Append(".RegisterServices(services, logger);\n");
        }

        if (registries.Count > 0)
        {
            sb.Append("            global::System.Collections.Generic.SortedSet<int> orders = new global::System.Collections.Generic.SortedSet<int>();\n");
            foreach (string registry in registries)
            {
                sb.Append("            orders.UnionWith(").Append(registry).Append(".DecoratorOrders);\n");
            }

            sb.Append("            foreach (int order in orders)\n");
            sb.Append("            {\n");
            foreach (string registry in registries)
            {
                sb.Append("                ").Append(registry).Append(".ApplyDecorators(services, order);\n");
            }

            sb.Append("            }\n");
        }

        sb.Append("            return services;\n");
        sb.Append("        }\n");
        sb.Append("    }\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    private static void WriteRegistration(StringBuilder sb, RegistrationModel registration)
    {
        foreach (ServiceModel service in registration.Services)
        {
            sb.Append("            ").Append(Registration).Append(".Apply(\n");
            sb.Append("                services,\n");
            sb.Append("                logger,\n");
            sb.Append("                ");
            WriteDescriptor(sb, registration, service);
            sb.Append(",\n");
            sb.Append("                ").Append(registration.Strategy).Append(");\n");
        }
    }

    private static void WriteDescriptor(StringBuilder sb, RegistrationModel registration, ServiceModel service)
    {
        string lifetime = registration.Lifetime;
        string? key = registration.Key;
        if (service.Forwarded && key is null)
        {
            sb.Append(Descriptor).Append('.').Append(lifetime).Append('<').Append(service.ServiceType)
                .Append(">(static sp => ").Append(Resolve).Append(".GetRequiredService<").Append(registration.ImplementationType)
                .Append(">(sp))");
        }
        else if (service.Forwarded)
        {
            sb.Append(Descriptor).Append(".Keyed").Append(lifetime).Append('<').Append(service.ServiceType).Append(">(")
                .Append(key).Append(", static (sp, _) => ").Append(ResolveKeyed).Append(".GetRequiredKeyedService<")
                .Append(registration.ImplementationType).Append(">(sp, ").Append(key).Append("))");
        }
        else if (key is null)
        {
            sb.Append(Descriptor).Append('.').Append(lifetime).Append("(typeof(").Append(service.ServiceType)
                .Append("), typeof(").Append(registration.ImplementationType).Append("))");
        }
        else
        {
            sb.Append("new ").Append(Descriptor).Append("(typeof(").Append(service.ServiceType).Append("), ").Append(key)
                .Append(", typeof(").Append(registration.ImplementationType).Append("), ").Append(Lifetime).Append('.')
                .Append(lifetime).Append(')');
        }
    }

    private static void WriteDecorator(StringBuilder sb, DecoratorModel decorator)
    {
        sb.Append("                    ").Append(Decoration).Append(".Decorate<").Append(decorator.ServiceType).Append(">(\n");
        sb.Append("                        services,\n");
        sb.Append("                        static (inner, sp) => new ").Append(decorator.DecoratorType).Append('(');
        for (int index = 0; index < decorator.Parameters.Count; index++)
        {
            sb.Append(index == 0 ? "\n" : ",\n");
            sb.Append("                            ").Append(FormatArgument(decorator.Parameters[index], decorator.Key));
        }

        sb.Append("),\n");
        sb.Append("                        serviceKey: ").Append(decorator.Key ?? "null").Append(");\n");
    }

    private static string FormatArgument(DecoratorParameterModel parameter, string? key) => parameter.Kind switch
    {
        DecoratorParameterKind.Inner => "inner",
        DecoratorParameterKind.ServiceKey => key is null
            ? "default(" + parameter.Type + ")!"
            : "(" + parameter.Type + ")(object)" + key,
        DecoratorParameterKind.Keyed => ResolveKeyed + ".GetRequiredKeyedService<" + parameter.Type + ">(sp, " + parameter.Value + ")",
        DecoratorParameterKind.Optional => "(" + parameter.Type + ")(sp.GetService(typeof(" + parameter.Type + ")) ?? (object?)" + parameter.Value + ")!",
        DecoratorParameterKind.Required => Resolve + ".GetRequiredService<" + parameter.Type + ">(sp)",
        _ => throw new ArgumentOutOfRangeException(nameof(parameter), parameter.Kind, "Unknown decorator parameter kind."),
    };
}
